const FORMULA_CATEGORIES = [
  'All', 'Algebra', 'Trigonometry', 'Coordinate Geometry', 'Calculus',
  'Matrices', 'Vectors', 'Statistics', 'Probability', 'Physics', 'Chemistry', 'Biology'
];

const FORMULAS = [
  // ===== ALGEBRA =====
  { category: 'Algebra', name: 'Quadratic Formula', formula: 'x = (-b ± √(b² - 4ac)) / 2a', note: 'Roots of ax² + bx + c = 0' },
  { category: 'Algebra', name: 'Discriminant', formula: 'D = b² - 4ac', note: 'D>0: 2 real roots, D=0: equal, D<0: imaginary' },
  { category: 'Algebra', name: 'Sum of Roots', formula: 'α + β = -b/a', note: 'For ax² + bx + c = 0' },
  { category: 'Algebra', name: 'Product of Roots', formula: 'αβ = c/a', note: 'For ax² + bx + c = 0' },
  { category: 'Algebra', name: 'AP nth term', formula: 'aₙ = a + (n-1)d', note: 'a=first term, d=common difference' },
  { category: 'Algebra', name: 'AP Sum (n terms)', formula: 'Sₙ = n/2 [2a + (n-1)d]', note: 'Sum of arithmetic progression' },
  { category: 'Algebra', name: 'AP Sum (last term)', formula: 'Sₙ = n/2 (a + l)', note: 'l = last term' },
  { category: 'Algebra', name: 'GP nth term', formula: 'aₙ = arⁿ⁻¹', note: 'r = common ratio' },
  { category: 'Algebra', name: 'GP Sum (finite)', formula: 'Sₙ = a(rⁿ-1)/(r-1)', note: 'r ≠ 1' },
  { category: 'Algebra', name: 'GP Sum (infinite)', formula: 'S = a/(1-r)', note: '|r| < 1' },
  { category: 'Algebra', name: 'HP nth term', formula: '1/aₙ = a + (n-1)d', note: 'Harmonic progression' },
  { category: 'Algebra', name: 'Binomial Theorem', formula: '(a+b)ⁿ = Σ ⁿCᵣ aⁿ⁻ʳ bʳ', note: 'r = 0 to n' },
  { category: 'Algebra', name: 'nCr', formula: 'ⁿCᵣ = n! / [r!(n-r)!]', note: 'Combination' },
  { category: 'Algebra', name: 'nPr', formula: 'ⁿPᵣ = n! / (n-r)!', note: 'Permutation' },
  { category: 'Algebra', name: 'Log Product', formula: 'logₐ(mn) = logₐm + logₐn', note: 'Logarithm rule' },
  { category: 'Algebra', name: 'Log Quotient', formula: 'logₐ(m/n) = logₐm - logₐn', note: 'Logarithm rule' },
  { category: 'Algebra', name: 'Log Power', formula: 'logₐ(mⁿ) = n·logₐm', note: 'Logarithm rule' },
  { category: 'Algebra', name: 'Change of Base', formula: 'logₐb = logᶜb / logᶜa', note: 'Any base c' },
  { category: 'Algebra', name: 'Complex Modulus', formula: '|z| = √(a² + b²)', note: 'z = a + ib' },
  { category: 'Algebra', name: 'Complex Argument', formula: 'arg(z) = tan⁻¹(b/a)', note: 'z = a + ib' },
  { category: 'Algebra', name: 'De Moivre', formula: '(cosθ + i sinθ)ⁿ = cos(nθ) + i sin(nθ)', note: 'Complex numbers' },
  { category: 'Algebra', name: 'Cube Roots of Unity', formula: '1, ω, ω² where ω = (-1+i√3)/2', note: 'ω³ = 1, 1+ω+ω² = 0' },
  { category: 'Algebra', name: 'AM ≥ GM ≥ HM', formula: 'AM = (a+b)/2, GM = √(ab), HM = 2ab/(a+b)', note: 'For positive numbers' },
  { category: 'Algebra', name: 'Sum of n²', formula: 'Σk² = n(n+1)(2n+1)/6', note: 'k=1 to n' },
  { category: 'Algebra', name: 'Sum of n³', formula: 'Σk³ = [n(n+1)/2]²', note: 'k=1 to n' },
  { category: 'Algebra', name: 'HCF × LCM', formula: 'HCF × LCM = a × b', note: 'For two numbers' },
  { category: 'Algebra', name: 'Remainder Theorem', formula: 'P(a) = remainder when P(x) divided by (x-a)', note: 'Polynomial division' },
  { category: 'Algebra', name: 'Factor Theorem', formula: '(x-a) is factor iff P(a) = 0', note: 'Polynomial factorization' },

  // ===== TRIGONOMETRY =====
  { category: 'Trigonometry', name: 'Pythagorean Identity', formula: 'sin²θ + cos²θ = 1', note: 'Fundamental identity' },
  { category: 'Trigonometry', name: '1 + tan²θ', formula: '1 + tan²θ = sec²θ', note: 'Pythagorean identity' },
  { category: 'Trigonometry', name: '1 + cot²θ', formula: '1 + cot²θ = cosec²θ', note: 'Pythagorean identity' },
  { category: 'Trigonometry', name: 'sin(A+B)', formula: 'sin(A+B) = sinA·cosB + cosA·sinB', note: 'Addition formula' },
  { category: 'Trigonometry', name: 'sin(A-B)', formula: 'sin(A-B) = sinA·cosB - cosA·sinB', note: 'Subtraction formula' },
  { category: 'Trigonometry', name: 'cos(A+B)', formula: 'cos(A+B) = cosA·cosB - sinA·sinB', note: 'Addition formula' },
  { category: 'Trigonometry', name: 'cos(A-B)', formula: 'cos(A-B) = cosA·cosB + sinA·sinB', note: 'Subtraction formula' },
  { category: 'Trigonometry', name: 'tan(A+B)', formula: 'tan(A+B) = (tanA+tanB)/(1-tanA·tanB)', note: 'Addition formula' },
  { category: 'Trigonometry', name: 'sin 2θ', formula: 'sin 2θ = 2 sinθ cosθ', note: 'Double angle' },
  { category: 'Trigonometry', name: 'cos 2θ', formula: 'cos 2θ = cos²θ - sin²θ = 2cos²θ-1 = 1-2sin²θ', note: 'Double angle' },
  { category: 'Trigonometry', name: 'tan 2θ', formula: 'tan 2θ = 2tanθ / (1-tan²θ)', note: 'Double angle' },
  { category: 'Trigonometry', name: 'sin 3θ', formula: 'sin 3θ = 3sinθ - 4sin³θ', note: 'Triple angle' },
  { category: 'Trigonometry', name: 'cos 3θ', formula: 'cos 3θ = 4cos³θ - 3cosθ', note: 'Triple angle' },
  { category: 'Trigonometry', name: 'sin A + sin B', formula: '2 sin((A+B)/2) cos((A-B)/2)', note: 'Sum to product' },
  { category: 'Trigonometry', name: 'cos A + cos B', formula: '2 cos((A+B)/2) cos((A-B)/2)', note: 'Sum to product' },
  { category: 'Trigonometry', name: 'sin A - sin B', formula: '2 cos((A+B)/2) sin((A-B)/2)', note: 'Difference to product' },
  { category: 'Trigonometry', name: '2 sinA cosB', formula: 'sin(A+B) + sin(A-B)', note: 'Product to sum' },
  { category: 'Trigonometry', name: 'General Solution sinθ', formula: 'θ = nπ + (-1)ⁿα', note: 'sinθ = sinα' },
  { category: 'Trigonometry', name: 'General Solution cosθ', formula: 'θ = 2nπ ± α', note: 'cosθ = cosα' },
  { category: 'Trigonometry', name: 'Height & Distance', formula: 'h = d·tanθ', note: 'θ = angle of elevation' },
  { category: 'Trigonometry', name: 'Radian-Degree', formula: 'π rad = 180°, 1° = π/180 rad', note: 'Conversion' },
  { category: 'Trigonometry', name: 'Arc Length', formula: 's = rθ', note: 'θ in radians' },
  { category: 'Trigonometry', name: 'Sector Area', formula: 'A = ½r²θ', note: 'θ in radians' },
  { category: 'Trigonometry', name: 'sin⁻¹x + cos⁻¹x', formula: 'π/2', note: 'Inverse trig identity' },

  // ===== COORDINATE GEOMETRY =====
  { category: 'Coordinate Geometry', name: 'Distance Formula', formula: 'd = √[(x₂-x₁)² + (y₂-y₁)²]', note: 'Between two points' },
  { category: 'Coordinate Geometry', name: 'Section Formula (internal)', formula: '((mx₂+nx₁)/(m+n), (my₂+ny₁)/(m+n))', note: 'Ratio m:n' },
  { category: 'Coordinate Geometry', name: 'Midpoint', formula: '((x₁+x₂)/2, (y₁+y₂)/2)', note: 'Middle point' },
  { category: 'Coordinate Geometry', name: 'Slope', formula: 'm = (y₂-y₁)/(x₂-x₁)', note: 'Gradient of line' },
  { category: 'Coordinate Geometry', name: 'Slope (angle)', formula: 'm = tanθ', note: 'θ = angle with x-axis' },
  { category: 'Coordinate Geometry', name: 'Line (slope-intercept)', formula: 'y = mx + c', note: 'm=slope, c=y-intercept' },
  { category: 'Coordinate Geometry', name: 'Line (two-point)', formula: 'y-y₁ = m(x-x₁)', note: 'Point-slope form' },
  { category: 'Coordinate Geometry', name: 'Line (intercept)', formula: 'x/a + y/b = 1', note: 'a=x-intercept, b=y-intercept' },
  { category: 'Coordinate Geometry', name: 'Line (normal)', formula: 'x cosα + y sinα = p', note: 'p = perpendicular distance from origin' },
  { category: 'Coordinate Geometry', name: 'Angle between lines', formula: 'tanθ = |(m₁-m₂)/(1+m₁m₂)|', note: 'Acute angle' },
  { category: 'Coordinate Geometry', name: 'Distance point to line', formula: 'd = |ax₁+by₁+c| / √(a²+b²)', note: 'Line ax+by+c=0' },
  { category: 'Coordinate Geometry', name: 'Circle (standard)', formula: '(x-h)² + (y-k)² = r²', note: 'Centre (h,k), radius r' },
  { category: 'Coordinate Geometry', name: 'Circle (general)', formula: 'x²+y²+2gx+2fy+c=0', note: 'Centre (-g,-f), r=√(g²+f²-c)' },
  { category: 'Coordinate Geometry', name: 'Parabola (standard)', formula: 'y² = 4ax', note: 'Focus (a,0), directrix x=-a' },
  { category: 'Coordinate Geometry', name: 'Ellipse (standard)', formula: 'x²/a² + y²/b² = 1', note: 'a>b, foci at (±c,0), c²=a²-b²' },
  { category: 'Coordinate Geometry', name: 'Hyperbola (standard)', formula: 'x²/a² - y²/b² = 1', note: 'c² = a²+b²' },
  { category: 'Coordinate Geometry', name: 'Eccentricity (ellipse)', formula: 'e = c/a = √(1-b²/a²)', note: 'e < 1' },
  { category: 'Coordinate Geometry', name: 'Eccentricity (hyperbola)', formula: 'e = c/a = √(1+b²/a²)', note: 'e > 1' },
  { category: 'Coordinate Geometry', name: '3D Distance', formula: 'd = √[(x₂-x₁)²+(y₂-y₁)²+(z₂-z₁)²]', note: 'Between 3D points' },
  { category: 'Coordinate Geometry', name: 'Direction Cosines', formula: 'l²+m²+n² = 1', note: 'l,m,n = direction cosines' },
  { category: 'Coordinate Geometry', name: 'Plane equation', formula: 'ax+by+cz+d=0', note: 'Normal vector (a,b,c)' },
  { category: 'Coordinate Geometry', name: 'Triangle Area', formula: 'A = ½|x₁(y₂-y₃)+x₂(y₃-y₁)+x₃(y₁-y₂)|', note: 'Vertices (x₁,y₁), (x₂,y₂), (x₃,y₃)' },

  // ===== CALCULUS =====
  { category: 'Calculus', name: 'Power Rule', formula: 'd/dx(xⁿ) = nxⁿ⁻¹', note: 'Basic derivative' },
  { category: 'Calculus', name: 'Constant Rule', formula: 'd/dx(c) = 0', note: 'c = constant' },
  { category: 'Calculus', name: 'Sum Rule', formula: '(u±v)\' = u\' ± v\'', note: 'Derivative of sum' },
  { category: 'Calculus', name: 'Product Rule', formula: '(uv)\' = u\'v + uv\'', note: 'Derivative of product' },
  { category: 'Calculus', name: 'Quotient Rule', formula: '(u/v)\' = (u\'v - uv\')/v²', note: 'Derivative of quotient' },
  { category: 'Calculus', name: 'Chain Rule', formula: 'd/dx[f(g(x))] = f\'(g(x))·g\'(x)', note: 'Composite function' },
  { category: 'Calculus', name: 'd/dx(sin x)', formula: 'cos x', note: 'Trig derivative' },
  { category: 'Calculus', name: 'd/dx(cos x)', formula: '-sin x', note: 'Trig derivative' },
  { category: 'Calculus', name: 'd/dx(tan x)', formula: 'sec²x', note: 'Trig derivative' },
  { category: 'Calculus', name: 'd/dx(eˣ)', formula: 'eˣ', note: 'Exponential derivative' },
  { category: 'Calculus', name: 'd/dx(ln x)', formula: '1/x', note: 'Log derivative' },
  { category: 'Calculus', name: 'd/dx(aˣ)', formula: 'aˣ ln a', note: 'General exponential' },
  { category: 'Calculus', name: 'Second Derivative Test', formula: 'f\'\'(c)>0 → min, f\'\'(c)<0 → max', note: 'At critical point c' },
  { category: 'Calculus', name: '∫xⁿ dx', formula: 'xⁿ⁺¹/(n+1) + C', note: 'n ≠ -1' },
  { category: 'Calculus', name: '∫1/x dx', formula: 'ln|x| + C', note: 'Log integral' },
  { category: 'Calculus', name: '∫eˣ dx', formula: 'eˣ + C', note: 'Exponential integral' },
  { category: 'Calculus', name: '∫sin x dx', formula: '-cos x + C', note: 'Trig integral' },
  { category: 'Calculus', name: '∫cos x dx', formula: 'sin x + C', note: 'Trig integral' },
  { category: 'Calculus', name: 'Integration by Parts', formula: '∫u dv = uv - ∫v du', note: 'LIATE rule for choosing u' },
  { category: 'Calculus', name: 'Definite Integral', formula: '∫ₐᵇ f(x)dx = F(b) - F(a)', note: 'Fundamental theorem' },
  { category: 'Calculus', name: 'Area under curve', formula: 'A = ∫ₐᵇ y dx', note: 'Between curve and x-axis' },
  { category: 'Calculus', name: 'Limit (standard)', formula: 'lim(x→0) sinx/x = 1', note: 'Important limit' },
  { category: 'Calculus', name: 'Limit (standard)', formula: 'lim(x→0) (1-cosx)/x = 0', note: 'Important limit' },
  { category: 'Calculus', name: 'Limit (e)', formula: 'lim(x→∞) (1+1/x)ˣ = e', note: 'Definition of e' },
  { category: 'Calculus', name: 'L\'Hôpital\'s Rule', formula: 'lim f/g = lim f\'/g\'', note: '0/0 or ∞/∞ form' },

  // ===== MATRICES =====
  { category: 'Matrices', name: 'Determinant 2×2', formula: '|A| = ad - bc', note: 'A = [[a,b],[c,d]]' },
  { category: 'Matrices', name: 'Inverse 2×2', formula: 'A⁻¹ = (1/|A|) [[d,-b],[-c,a]]', note: '|A| ≠ 0' },
  { category: 'Matrices', name: 'Adjoint', formula: 'adj(A) = transpose of cofactor matrix', note: 'A⁻¹ = adj(A)/|A|' },
  { category: 'Matrices', name: 'Cramer\'s Rule', formula: 'x = |A₁|/|A|, y = |A₂|/|A|', note: 'System of equations' },
  { category: 'Matrices', name: '|AB| = |A|·|B|', formula: 'Determinant of product', note: 'Square matrices' },
  { category: 'Matrices', name: '|kA| = kⁿ|A|', formula: 'n = order of matrix', note: 'Scalar multiplication' },

  // ===== VECTORS =====
  { category: 'Vectors', name: 'Magnitude', formula: '|a| = √(a₁² + a₂² + a₃²)', note: '3D vector' },
  { category: 'Vectors', name: 'Dot Product', formula: 'a·b = |a||b|cosθ = a₁b₁+a₂b₂+a₃b₃', note: 'Scalar result' },
  { category: 'Vectors', name: 'Cross Product', formula: '|a×b| = |a||b|sinθ', note: 'Vector result, ⊥ to both' },
  { category: 'Vectors', name: 'Projection of a on b', formula: 'proj = (a·b/|b|²)b', note: 'Vector projection' },
  { category: 'Vectors', name: 'Work Done', formula: 'W = F·d = |F||d|cosθ', note: 'Dot product application' },
  { category: 'Vectors', name: 'Unit Vector', formula: 'â = a/|a|', note: 'Direction only' },
  { category: 'Vectors', name: 'Triangle Law', formula: 'a + b = c', note: 'Vector addition' },

  // ===== STATISTICS =====
  { category: 'Statistics', name: 'Mean', formula: 'x̄ = Σxᵢ/n', note: 'Arithmetic mean' },
  { category: 'Statistics', name: 'Median (odd n)', formula: 'Middle value when sorted', note: 'n odd' },
  { category: 'Statistics', name: 'Median (even n)', formula: '(n/2 th + (n/2+1)th) / 2', note: 'n even' },
  { category: 'Statistics', name: 'Mode', formula: 'Most frequent value', note: 'Can be multiple modes' },
  { category: 'Statistics', name: 'Variance', formula: 'σ² = Σ(xᵢ-x̄)²/n', note: 'Population variance' },
  { category: 'Statistics', name: 'Standard Deviation', formula: 'σ = √σ²', note: 'Square root of variance' },
  { category: 'Statistics', name: 'Combined Mean', formula: 'x̄ = (n₁x̄₁+n₂x̄₂)/(n₁+n₂)', note: 'Two groups' },
  { category: 'Statistics', name: 'Coefficient of Variation', formula: 'CV = (σ/x̄)×100%', note: 'Relative dispersion' },

  // ===== PROBABILITY =====
  { category: 'Probability', name: 'Basic Probability', formula: 'P(A) = n(A)/n(S)', note: 'Favourable/Total outcomes' },
  { category: 'Probability', name: 'Complement', formula: 'P(A\') = 1 - P(A)', note: 'Not A' },
  { category: 'Probability', name: 'Addition Rule', formula: 'P(A∪B) = P(A)+P(B)-P(A∩B)', note: 'Union of events' },
  { category: 'Probability', name: 'Independent Events', formula: 'P(A∩B) = P(A)·P(B)', note: 'Events independent' },
  { category: 'Probability', name: 'Conditional', formula: 'P(A|B) = P(A∩B)/P(B)', note: 'A given B' },
  { category: 'Probability', name: 'Bayes Theorem', formula: 'P(A|B) = P(B|A)·P(A)/P(B)', note: 'Reverse conditional' },
  { category: 'Probability', name: 'Binomial Distribution', formula: 'P(X=r) = ⁿCᵣ pʳ(1-p)ⁿ⁻ʳ', note: 'n trials, r successes' },

  // ===== PHYSICS — MECHANICS =====
  { category: 'Physics', name: 'Speed', formula: 'v = d/t', note: 'Distance/time' },
  { category: 'Physics', name: 'Velocity', formula: 'v = ds/dt', note: 'Displacement/time' },
  { category: 'Physics', name: 'Acceleration', formula: 'a = dv/dt', note: 'Rate of change of velocity' },
  { category: 'Physics', name: 'Equations of Motion', formula: 'v = u + at', note: '1st equation' },
  { category: 'Physics', name: 'Equations of Motion', formula: 's = ut + ½at²', note: '2nd equation' },
  { category: 'Physics', name: 'Equations of Motion', formula: 'v² = u² + 2as', note: '3rd equation' },
  { category: 'Physics', name: 'Newton\'s 2nd Law', formula: 'F = ma', note: 'Force = mass × acceleration' },
  { category: 'Physics', name: 'Momentum', formula: 'p = mv', note: 'Mass × velocity' },
  { category: 'Physics', name: 'Impulse', formula: 'J = FΔt = Δp', note: 'Change in momentum' },
  { category: 'Physics', name: 'Weight', formula: 'W = mg', note: 'g = 9.8 m/s²' },
  { category: 'Physics', name: 'Kinetic Energy', formula: 'KE = ½mv²', note: 'Energy of motion' },
  { category: 'Physics', name: 'Potential Energy', formula: 'PE = mgh', note: 'Gravitational PE' },
  { category: 'Physics', name: 'Work Done', formula: 'W = F·d·cosθ', note: 'θ = angle between F and d' },
  { category: 'Physics', name: 'Power', formula: 'P = W/t = F·v', note: 'Rate of doing work' },
  { category: 'Physics', name: 'Centripetal Force', formula: 'F = mv²/r', note: 'Circular motion' },
  { category: 'Physics', name: 'Centripetal Acceleration', formula: 'a = v²/r = ω²r', note: 'Circular motion' },
  { category: 'Physics', name: 'Angular Velocity', formula: 'ω = 2πf = 2π/T', note: 'Radians per second' },
  { category: 'Physics', name: 'Projectile Range', formula: 'R = u²sin2θ/g', note: 'Max at θ=45°' },
  { category: 'Physics', name: 'Projectile Max Height', formula: 'H = u²sin²θ/2g', note: 'Vertical motion' },
  { category: 'Physics', name: 'Projectile Time of Flight', formula: 'T = 2u sinθ/g', note: 'Total flight time' },
  { category: 'Physics', name: 'Friction', formula: 'f = μN', note: 'μ = coefficient, N = normal force' },
  { category: 'Physics', name: 'Pressure', formula: 'P = F/A', note: 'Force per unit area' },
  { category: 'Physics', name: 'Archimedes Principle', formula: 'F_buoyant = ρVg', note: 'ρ=fluid density, V=displaced volume' },
  { category: 'Physics', name: 'Density', formula: 'ρ = m/V', note: 'Mass per unit volume' },
  { category: 'Physics', name: 'Pascal\'s Law', formula: 'P = F/A (same at all points)', note: 'Hydraulic systems' },

  // ===== PHYSICS — HEAT & THERMODYNAMICS =====
  { category: 'Physics', name: 'Heat', formula: 'Q = mcΔT', note: 'Specific heat capacity' },
  { category: 'Physics', name: 'Latent Heat', formula: 'Q = mL', note: 'L = latent heat' },
  { category: 'Physics', name: 'Thermal Expansion', formula: 'ΔL = αLΔT', note: 'Linear expansion' },
  { category: 'Physics', name: 'Ideal Gas Law', formula: 'PV = nRT', note: 'R = 8.314 J/mol·K' },
  { category: 'Physics', name: 'Boyle\'s Law', formula: 'P₁V₁ = P₂V₂', note: 'T constant' },
  { category: 'Physics', name: 'Charles\' Law', formula: 'V₁/T₁ = V₂/T₂', note: 'P constant' },
  { category: 'Physics', name: 'Efficiency', formula: 'η = (useful output/input) × 100%', note: 'Machine efficiency' },

  // ===== PHYSICS — WAVES & OPTICS =====
  { category: 'Physics', name: 'Wave Speed', formula: 'v = fλ', note: 'v = frequency × wavelength' },
  { category: 'Physics', name: 'Frequency', formula: 'f = 1/T', note: 'T = time period' },
  { category: 'Physics', name: 'Doppler Effect', formula: 'f\' = f(v±v₀)/(v∓vₛ)', note: 'Moving source/observer' },
  { category: 'Physics', name: 'Mirror Formula', formula: '1/f = 1/v + 1/u', note: 'f=focal, v=image, u=object' },
  { category: 'Physics', name: 'Lens Formula', formula: '1/f = 1/v - 1/u', note: 'Sign convention' },
  { category: 'Physics', name: 'Magnification', formula: 'm = -v/u = h\'/h', note: 'Image/object height ratio' },
  { category: 'Physics', name: 'Refractive Index', formula: 'n = c/v = sin i/sin r', note: 'Snell\'s law' },
  { category: 'Physics', name: 'Critical Angle', formula: 'sin θc = 1/n', note: 'Total internal reflection' },
  { category: 'Physics', name: 'Power of Lens', formula: 'P = 1/f (diopters)', note: 'f in metres' },
  { category: 'Physics', name: 'Simple Pendulum', formula: 'T = 2π√(L/g)', note: 'Time period' },
  { category: 'Physics', name: 'Spring (SHM)', formula: 'T = 2π√(m/k)', note: 'k = spring constant' },

  // ===== PHYSICS — ELECTRICITY & MAGNETISM =====
  { category: 'Physics', name: 'Ohm\'s Law', formula: 'V = IR', note: 'Voltage = Current × Resistance' },
  { category: 'Physics', name: 'Resistance', formula: 'R = ρL/A', note: 'ρ=resistivity, L=length, A=area' },
  { category: 'Physics', name: 'Series Resistance', formula: 'R = R₁+R₂+R₃+...', note: 'Resistors in series' },
  { category: 'Physics', name: 'Parallel Resistance', formula: '1/R = 1/R₁+1/R₂+...', note: 'Resistors in parallel' },
  { category: 'Physics', name: 'Electrical Power', formula: 'P = VI = I²R = V²/R', note: 'Power formulas' },
  { category: 'Physics', name: 'Electrical Energy', formula: 'E = Pt = VIt', note: 'Energy consumed' },
  { category: 'Physics', name: 'Coulomb\'s Law', formula: 'F = kq₁q₂/r²', note: 'k = 9×10⁹ N·m²/C²' },
  { category: 'Physics', name: 'Electric Field', formula: 'E = F/q = kQ/r²', note: 'Field intensity' },
  { category: 'Physics', name: 'Capacitance', formula: 'C = Q/V', note: 'Charge/potential difference' },
  { category: 'Physics', name: 'Parallel Plate Capacitor', formula: 'C = ε₀A/d', note: 'A=area, d=separation' },
  { category: 'Physics', name: 'Magnetic Force', formula: 'F = BIL sinθ', note: 'On current-carrying wire' },
  { category: 'Physics', name: 'Faraday\'s Law', formula: 'ε = -dΦ/dt', note: 'Electromagnetic induction' },
  { category: 'Physics', name: 'Transformer', formula: 'Vₛ/Vₚ = Nₛ/Nₚ', note: 'Voltage ratio = turns ratio' },

  // ===== PHYSICS — MODERN =====
  { category: 'Physics', name: 'Einstein Mass-Energy', formula: 'E = mc²', note: 'c = 3×10⁸ m/s' },
  { category: 'Physics', name: 'Photoelectric Effect', formula: 'KE_max = hf - φ', note: 'h=Planck\'s constant, φ=work function' },
  { category: 'Physics', name: 'de Broglie Wavelength', formula: 'λ = h/p = h/mv', note: 'Matter waves' },

  // ===== CHEMISTRY =====
  { category: 'Chemistry', name: 'Moles', formula: 'n = m/M = N/Nₐ', note: 'm=mass, M=molar mass, N=particles' },
  { category: 'Chemistry', name: 'Molarity', formula: 'M = n/V (mol/L)', note: 'Concentration' },
  { category: 'Chemistry', name: 'Molality', formula: 'm = n/mass of solvent (kg)', note: 'mol/kg' },
  { category: 'Chemistry', name: 'Normality', formula: 'N = n × valency / V', note: 'Equivalent concentration' },
  { category: 'Chemistry', name: 'Dilution', formula: 'M₁V₁ = M₂V₂', note: 'Before and after dilution' },
  { category: 'Chemistry', name: 'Ideal Gas', formula: 'PV = nRT', note: 'Gas equation' },
  { category: 'Chemistry', name: 'Avogadro\'s Number', formula: 'Nₐ = 6.022 × 10²³ mol⁻¹', note: 'Particles per mole' },
  { category: 'Chemistry', name: 'pH', formula: 'pH = -log[H⁺]', note: 'Acidity measure' },
  { category: 'Chemistry', name: 'pOH', formula: 'pOH = -log[OH⁻]', note: 'Basicity measure' },
  { category: 'Chemistry', name: 'pH + pOH', formula: 'pH + pOH = 14', note: 'At 25°C' },
  { category: 'Chemistry', name: 'Percentage Composition', formula: '% = (mass of element/molar mass) × 100', note: 'In compound' },
  { category: 'Chemistry', name: 'Empirical Formula', formula: 'Simplest whole number ratio of atoms', note: 'From % composition' },
  { category: 'Chemistry', name: 'Faraday\'s Law (electrolysis)', formula: 'm = (EIt)/(96500)', note: 'E = equivalent weight' },
  { category: 'Chemistry', name: 'Rate of Reaction', formula: 'Rate = Δ[conc]/Δt', note: 'Change in concentration per time' },
  { category: 'Chemistry', name: 'Arrhenius Equation', formula: 'k = Ae^(-Ea/RT)', note: 'Temperature dependence of rate' },
  { category: 'Chemistry', name: 'Raoult\'s Law', formula: 'P = P° × mole fraction', note: 'Vapour pressure lowering' },
  { category: 'Chemistry', name: 'Oxidation Number', formula: 'Sum = charge on ion/molecule', note: 'Conservation in reactions' },

  // ===== BIOLOGY =====
  { category: 'Biology', name: 'Photosynthesis', formula: '6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂', note: 'In presence of sunlight & chlorophyll' },
  { category: 'Biology', name: 'Respiration', formula: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + Energy', note: 'Cellular respiration' },
  { category: 'Biology', name: 'Blood Groups', formula: 'A, B, AB, O — Rh+ or Rh-', note: '4 main groups' },
  { category: 'Biology', name: 'Mendel\'s Law', formula: 'F₂ ratio = 3:1 (monohybrid)', note: 'Dominant:Recessive phenotype' }
];
