const FORMULA_CATEGORIES = [
  'All', 'Algebra', 'Trigonometry', 'Coordinate Geometry', 'Calculus',
  'Differential Equations', 'Matrices', 'Vectors', 'Statistics', 'Probability',
  'Physics', 'Chemistry', 'Biology'
];

const FORMULAS = [
  // ===== ALGEBRA =====
  { category: 'Algebra', name: 'Quadratic Formula', formula: 'x = (-b ± √(b² - 4ac)) / 2a', note: 'Roots of ax² + bx + c = 0' },
  { category: 'Algebra', name: 'Discriminant', formula: 'D = b² - 4ac', note: 'D>0: 2 real roots, D=0: equal, D<0: imaginary' },
  { category: 'Algebra', name: 'Sum of Roots', formula: 'α + β = -b/a', note: 'For ax² + bx + c = 0' },
  { category: 'Algebra', name: 'Product of Roots', formula: 'αβ = c/a', note: 'For ax² + bx + c = 0' },
  { category: 'Algebra', name: 'AP nth term', formula: 'aₙ = a + (n-1)d', note: 'a=first term, d=common difference' },
  { category: 'Algebra', name: 'AP Sum (n terms)', formula: 'Sₙ = n/2 [2a + (n-1)d]', note: 'Sum of arithmetic progression' },
  { category: 'Algebra', name: 'AP Sum (last term)', formula: 'Sₙ = n/2 (a + l)', note: 'l = last term' },
  { category: 'Algebra', name: 'GP nth term', formula: 'aₙ = arⁿ⁻¹', note: 'r = common ratio' },
  { category: 'Algebra', name: 'GP Sum (finite)', formula: 'Sₙ = a(rⁿ-1)/(r-1)', note: 'r ≠ 1' },
  { category: 'Algebra', name: 'GP Sum (infinite)', formula: 'S = a/(1-r)', note: '|r| < 1' },
  { category: 'Algebra', name: 'HP nth term', formula: '1/aₙ = a + (n-1)d', note: 'Harmonic progression' },
  { category: 'Algebra', name: 'Binomial Theorem', formula: '(a+b)ⁿ = Σ ⁿCᵣ aⁿ⁻ʳ bʳ', note: 'r = 0 to n' },
  { category: 'Algebra', name: 'nCr', formula: 'ⁿCᵣ = n! / [r!(n-r)!]', note: 'Combination' },
  { category: 'Algebra', name: 'nPr', formula: 'ⁿPᵣ = n! / (n-r)!', note: 'Permutation' },
  { category: 'Algebra', name: 'Log Product', formula: 'logₐ(mn) = logₐm + logₐn', note: 'Logarithm rule' },
  { category: 'Algebra', name: 'Log Quotient', formula: 'logₐ(m/n) = logₐm - logₐn', note: 'Logarithm rule' },
  { category: 'Algebra', name: 'Log Power', formula: 'logₐ(mⁿ) = n·logₐm', note: 'Logarithm rule' },
  { category: 'Algebra', name: 'Change of Base', formula: 'logₐb = logᶜb / logᶜa', note: 'Any base c' },
  { category: 'Algebra', name: 'Complex Modulus', formula: '|z| = √(a² + b²)', note: 'z = a + ib' },
  { category: 'Algebra', name: 'Complex Argument', formula: 'arg(z) = tan⁻¹(b/a)', note: 'z = a + ib' },
  { category: 'Algebra', name: 'De Moivre', formula: '(cosθ + i sinθ)ⁿ = cos(nθ) + i sin(nθ)', note: 'Complex numbers' },
  { category: 'Algebra', name: 'Cube Roots of Unity', formula: '1, ω, ω² where ω = (-1+i√3)/2', note: 'ω³ = 1, 1+ω+ω² = 0' },
  { category: 'Algebra', name: 'AM ≥ GM ≥ HM', formula: 'AM = (a+b)/2, GM = √(ab), HM = 2ab/(a+b)', note: 'For positive numbers' },
  { category: 'Algebra', name: 'Sum of n²', formula: 'Σk² = n(n+1)(2n+1)/6', note: 'k=1 to n' },
  { category: 'Algebra', name: 'Sum of n³', formula: 'Σk³ = [n(n+1)/2]²', note: 'k=1 to n' },
  { category: 'Algebra', name: 'HCF × LCM', formula: 'HCF × LCM = a × b', note: 'For two numbers' },
  { category: 'Algebra', name: 'Remainder Theorem', formula: 'P(a) = remainder when P(x) divided by (x-a)', note: 'Polynomial division' },
  { category: 'Algebra', name: 'Factor Theorem', formula: '(x-a) is factor iff P(a) = 0', note: 'Polynomial factorization' },

  // ===== TRIGONOMETRY =====
  { category: 'Trigonometry', name: 'Pythagorean Identity', formula: 'sin²θ + cos²θ = 1', note: 'Fundamental identity' },
  { category: 'Trigonometry', name: '1 + tan²θ', formula: '1 + tan²θ = sec²θ', note: 'Pythagorean identity' },
  { category: 'Trigonometry', name: '1 + cot²θ', formula: '1 + cot²θ = cosec²θ', note: 'Pythagorean identity' },
  { category: 'Trigonometry', name: 'sin(A+B)', formula: 'sin(A+B) = sinA·cosB + cosA·sinB', note: 'Addition formula' },
  { category: 'Trigonometry', name: 'sin(A-B)', formula: 'sin(A-B) = sinA·cosB - cosA·sinB', note: 'Subtraction formula' },
  { category: 'Trigonometry', name: 'cos(A+B)', formula: 'cos(A+B) = cosA·cosB - sinA·sinB', note: 'Addition formula' },
  { category: 'Trigonometry', name: 'cos(A-B)', formula: 'cos(A-B) = cosA·cosB + sinA·sinB', note: 'Subtraction formula' },
  { category: 'Trigonometry', name: 'tan(A+B)', formula: 'tan(A+B) = (tanA+tanB)/(1-tanA·tanB)', note: 'Addition formula' },
  { category: 'Trigonometry', name: 'sin 2θ', formula: 'sin 2θ = 2 sinθ cosθ', note: 'Double angle' },
  { category: 'Trigonometry', name: 'cos 2θ', formula: 'cos 2θ = cos²θ - sin²θ = 2cos²θ-1 = 1-2sin²θ', note: 'Double angle' },
  { category: 'Trigonometry', name: 'tan 2θ', formula: 'tan 2θ = 2tanθ / (1-tan²θ)', note: 'Double angle' },
  { category: 'Trigonometry', name: 'sin 3θ', formula: 'sin 3θ = 3sinθ - 4sin³θ', note: 'Triple angle' },
  { category: 'Trigonometry', name: 'cos 3θ', formula: 'cos 3θ = 4cos³θ - 3cosθ', note: 'Triple angle' },
  { category: 'Trigonometry', name: 'sin A + sin B', formula: '2 sin((A+B)/2) cos((A-B)/2)', note: 'Sum to product' },
  { category: 'Trigonometry', name: 'cos A + cos B', formula: '2 cos((A+B)/2) cos((A-B)/2)', note: 'Sum to product' },
  { category: 'Trigonometry', name: 'sin A - sin B', formula: '2 cos((A+B)/2) sin((A-B)/2)', note: 'Difference to product' },
  { category: 'Trigonometry', name: '2 sinA cosB', formula: 'sin(A+B) + sin(A-B)', note: 'Product to sum' },
  { category: 'Trigonometry', name: 'General Solution sinθ', formula: 'θ = nπ + (-1)ⁿα', note: 'sinθ = sinα' },
  { category: 'Trigonometry', name: 'General Solution cosθ', formula: 'θ = 2nπ ± α', note: 'cosθ = cosα' },
  { category: 'Trigonometry', name: 'Height & Distance', formula: 'h = d·tanθ', note: 'θ = angle of elevation' },
  { category: 'Trigonometry', name: 'Radian-Degree', formula: 'π rad = 180°, 1° = π/180 rad', note: 'Conversion' },
  { category: 'Trigonometry', name: 'Arc Length', formula: 's = rθ', note: 'θ in radians' },
  { category: 'Trigonometry', name: 'Sector Area', formula: 'A = ½r²θ', note: 'θ in radians' },
  { category: 'Trigonometry', name: 'sin⁻¹x + cos⁻¹x', formula: 'π/2', note: 'Inverse trig identity' },

  // ===== COORDINATE GEOMETRY =====
  { category: 'Coordinate Geometry', name: 'Distance Formula', formula: 'd = √[(x₂-x₁)² + (y₂-y₁)²]', note: 'Between two points' },
  { category: 'Coordinate Geometry', name: 'Section Formula (internal)', formula: '((mx₂+nx₁)/(m+n), (my₂+ny₁)/(m+n))', note: 'Ratio m:n' },
  { category: 'Coordinate Geometry', name: 'Midpoint', formula: '((x₁+x₂)/2, (y₁+y₂)/2)', note: 'Middle point' },
  { category: 'Coordinate Geometry', name: 'Slope', formula: 'm = (y₂-y₁)/(x₂-x₁)', note: 'Gradient of line' },
  { category: 'Coordinate Geometry', name: 'Slope (angle)', formula: 'm = tanθ', note: 'θ = angle with x-axis' },
  { category: 'Coordinate Geometry', name: 'Line (slope-intercept)', formula: 'y = mx + c', note: 'm=slope, c=y-intercept' },
  { category: 'Coordinate Geometry', name: 'Line (two-point)', formula: 'y-y₁ = m(x-x₁)', note: 'Point-slope form' },
  { category: 'Coordinate Geometry', name: 'Line (intercept)', formula: 'x/a + y/b = 1', note: 'a=x-intercept, b=y-intercept' },
  { category: 'Coordinate Geometry', name: 'Line (normal)', formula: 'x cosα + y sinα = p', note: 'p = perpendicular distance from origin' },
  { category: 'Coordinate Geometry', name: 'Angle between lines', formula: 'tanθ = |(m₁-m₂)/(1+m₁m₂)|', note: 'Acute angle' },
  { category: 'Coordinate Geometry', name: 'Distance point to line', formula: 'd = |ax₁+by₁+c| / √(a²+b²)', note: 'Line ax+by+c=0' },
  { category: 'Coordinate Geometry', name: 'Circle (standard)', formula: '(x-h)² + (y-k)² = r²', note: 'Centre (h,k), radius r' },
  { category: 'Coordinate Geometry', name: 'Circle (general)', formula: 'x²+y²+2gx+2fy+c=0', note: 'Centre (-g,-f), r=√(g²+f²-c)' },
  { category: 'Coordinate Geometry', name: 'Parabola (standard)', formula: 'y² = 4ax', note: 'Focus (a,0), directrix x=-a' },
  { category: 'Coordinate Geometry', name: 'Ellipse (standard)', formula: 'x²/a² + y²/b² = 1', note: 'a>b, foci at (±c,0), c²=a²-b²' },
  { category: 'Coordinate Geometry', name: 'Hyperbola (standard)', formula: 'x²/a² - y²/b² = 1', note: 'c² = a²+b²' },
  { category: 'Coordinate Geometry', name: 'Eccentricity (ellipse)', formula: 'e = c/a = √(1-b²/a²)', note: 'e < 1' },
  { category: 'Coordinate Geometry', name: 'Eccentricity (hyperbola)', formula: 'e = c/a = √(1+b²/a²)', note: 'e > 1' },
  { category: 'Coordinate Geometry', name: '3D Distance', formula: 'd = √[(x₂-x₁)²+(y₂-y₁)²+(z₂-z₁)²]', note: 'Between 3D points' },
  { category: 'Coordinate Geometry', name: 'Direction Cosines', formula: 'l²+m²+n² = 1', note: 'l,m,n = direction cosines' },
  { category: 'Coordinate Geometry', name: 'Plane equation', formula: 'ax+by+cz+d=0', note: 'Normal vector (a,b,c)' },
  { category: 'Coordinate Geometry', name: 'Triangle Area', formula: 'A = ½|x₁(y₂-y₃)+x₂(y₃-y₁)+x₃(y₁-y₂)|', note: 'Vertices (x₁,y₁), (x₂,y₂), (x₃,y₃)' },

  // ===== CALCULUS =====
  { category: 'Calculus', name: 'Power Rule', formula: 'd/dx(xⁿ) = nxⁿ⁻¹', note: 'Basic derivative' },
  { category: 'Calculus', name: 'Constant Rule', formula: 'd/dx(c) = 0', note: 'c = constant' },
  { category: 'Calculus', name: 'Sum Rule', formula: '(u±v)\' = u\' ± v\'', note: 'Derivative of sum' },
  { category: 'Calculus', name: 'Product Rule', formula: '(uv)\' = u\'v + uv\'', note: 'Derivative of product' },
  { category: 'Calculus', name: 'Quotient Rule', formula: '(u/v)\' = (u\'v - uv\')/v²', note: 'Derivative of quotient' },
  { category: 'Calculus', name: 'Chain Rule', formula: 'd/dx[f(g(x))] = f\'(g(x))·g\'(x)', note: 'Composite function' },
  { category: 'Calculus', name: 'd/dx(sin x)', formula: 'cos x', note: 'Trig derivative' },
  { category: 'Calculus', name: 'd/dx(cos x)', formula: '-sin x', note: 'Trig derivative' },
  { category: 'Calculus', name: 'd/dx(tan x)', formula: 'sec²x', note: 'Trig derivative' },
  { category: 'Calculus', name: 'd/dx(eˣ)', formula: 'eˣ', note: 'Exponential derivative' },
  { category: 'Calculus', name: 'd/dx(ln x)', formula: '1/x', note: 'Log derivative' },
  { category: 'Calculus', name: 'd/dx(aˣ)', formula: 'aˣ ln a', note: 'General exponential' },
  { category: 'Calculus', name: 'Second Derivative Test', formula: 'f\'\'(c)>0 → min, f\'\'(c)<0 → max', note: 'At critical point c' },
  { category: 'Calculus', name: '∫xⁿ dx', formula: 'xⁿ⁺¹/(n+1) + C', note: 'n ≠ -1' },
  { category: 'Calculus', name: '∫1/x dx', formula: 'ln|x| + C', note: 'Log integral' },
  { category: 'Calculus', name: '∫eˣ dx', formula: 'eˣ + C', note: 'Exponential integral' },
  { category: 'Calculus', name: '∫sin x dx', formula: '-cos x + C', note: 'Trig integral' },
  { category: 'Calculus', name: '∫cos x dx', formula: 'sin x + C', note: 'Trig integral' },
  { category: 'Calculus', name: 'Integration by Parts', formula: '∫u dv = uv - ∫v du', note: 'LIATE rule for choosing u' },
  { category: 'Calculus', name: 'Definite Integral', formula: '∫ₐᵇ f(x)dx = F(b) - F(a)', note: 'Fundamental theorem' },
  { category: 'Calculus', name: 'Area under curve', formula: 'A = ∫ₐᵇ y dx', note: 'Between curve and x-axis' },
  { category: 'Calculus', name: 'Limit (standard)', formula: 'lim(x→0) sinx/x = 1', note: 'Important limit' },
  { category: 'Calculus', name: 'Limit (standard)', formula: 'lim(x→0) (1-cosx)/x = 0', note: 'Important limit' },
  { category: 'Calculus', name: 'Limit (e)', formula: 'lim(x→∞) (1+1/x)ˣ = e', note: 'Definition of e' },
  { category: 'Calculus', name: 'L\'Hôpital\'s Rule', formula: 'lim f/g = lim f\'/g\'', note: '0/0 or ∞/∞ form' },

  // ===== MATRICES =====
  { category: 'Matrices', name: 'Determinant 2×2', formula: '|A| = ad - bc', note: 'A = [[a,b],[c,d]]' },
  { category: 'Matrices', name: 'Inverse 2×2', formula: 'A⁻¹ = (1/|A|) [[d,-b],[-c,a]]', note: '|A| ≠ 0' },
  { category: 'Matrices', name: 'Adjoint', formula: 'adj(A) = transpose of cofactor matrix', note: 'A⁻¹ = adj(A)/|A|' },
  { category: 'Matrices', name: 'Cramer\'s Rule', formula: 'x = |A₁|/|A|, y = |A₂|/|A|', note: 'System of equations' },
  { category: 'Matrices', name: '|AB| = |A|·|B|', formula: 'Determinant of product', note: 'Square matrices' },
  { category: 'Matrices', name: '|kA| = kⁿ|A|', formula: 'n = order of matrix', note: 'Scalar multiplication' },

  // ===== VECTORS =====
  { category: 'Vectors', name: 'Magnitude', formula: '|a| = √(a₁² + a₂² + a₃²)', note: '3D vector' },
  { category: 'Vectors', name: 'Dot Product', formula: 'a·b = |a||b|cosθ = a₁b₁+a₂b₂+a₃b₃', note: 'Scalar result' },
  { category: 'Vectors', name: 'Cross Product', formula: '|a×b| = |a||b|sinθ', note: 'Vector result, ⊥ to both' },
  { category: 'Vectors', name: 'Projection of a on b', formula: 'proj = (a·b/|b|²)b', note: 'Vector projection' },
  { category: 'Vectors', name: 'Work Done', formula: 'W = F·d = |F||d|cosθ', note: 'Dot product application' },
  { category: 'Vectors', name: 'Unit Vector', formula: 'â = a/|a|', note: 'Direction only' },
  { category: 'Vectors', name: 'Triangle Law', formula: 'a + b = c', note: 'Vector addition' },

  // ===== STATISTICS =====
  { category: 'Statistics', name: 'Mean', formula: 'x̄ = Σxᵢ/n', note: 'Arithmetic mean' },
  { category: 'Statistics', name: 'Median (odd n)', formula: 'Middle value when sorted', note: 'n odd' },
  { category: 'Statistics', name: 'Median (even n)', formula: '(n/2 th + (n/2+1)th) / 2', note: 'n even' },
  { category: 'Statistics', name: 'Mode', formula: 'Most frequent value', note: 'Can be multiple modes' },
  { category: 'Statistics', name: 'Variance', formula: 'σ² = Σ(xᵢ-x̄)²/n', note: 'Population variance' },
  { category: 'Statistics', name: 'Standard Deviation', formula: 'σ = √σ²', note: 'Square root of variance' },
  { category: 'Statistics', name: 'Combined Mean', formula: 'x̄ = (n₁x̄₁+n₂x̄₂)/(n₁+n₂)', note: 'Two groups' },
  { category: 'Statistics', name: 'Coefficient of Variation', formula: 'CV = (σ/x̄)×100%', note: 'Relative dispersion' },

  // ===== PROBABILITY =====
  { category: 'Probability', name: 'Basic Probability', formula: 'P(A) = n(A)/n(S)', note: 'Favourable/Total outcomes' },
  { category: 'Probability', name: 'Complement', formula: 'P(A\') = 1 - P(A)', note: 'Not A' },
  { category: 'Probability', name: 'Addition Rule', formula: 'P(A∪B) = P(A)+P(B)-P(A∩B)', note: 'Union of events' },
  { category: 'Probability', name: 'Independent Events', formula: 'P(A∩B) = P(A)·P(B)', note: 'Events independent' },
  { category: 'Probability', name: 'Conditional', formula: 'P(A|B) = P(A∩B)/P(B)', note: 'A given B' },
  { category: 'Probability', name: 'Bayes Theorem', formula: 'P(A|B) = P(B|A)·P(A)/P(B)', note: 'Reverse conditional' },
  { category: 'Probability', name: 'Binomial Distribution', formula: 'P(X=r) = ⁿCᵣ pʳ(1-p)ⁿ⁻ʳ', note: 'n trials, r successes' },

  // ===== PHYSICS — MECHANICS =====
  { category: 'Physics', name: 'Speed', formula: 'v = d/t', note: 'Distance/time' },
  { category: 'Physics', name: 'Velocity', formula: 'v = ds/dt', note: 'Displacement/time' },
  { category: 'Physics', name: 'Acceleration', formula: 'a = dv/dt', note: 'Rate of change of velocity' },
  { category: 'Physics', name: 'Equations of Motion', formula: 'v = u + at', note: '1st equation' },
  { category: 'Physics', name: 'Equations of Motion', formula: 's = ut + ½at²', note: '2nd equation' },
  { category: 'Physics', name: 'Equations of Motion', formula: 'v² = u² + 2as', note: '3rd equation' },
  { category: 'Physics', name: 'Newton\'s 2nd Law', formula: 'F = ma', note: 'Force = mass × acceleration' },
  { category: 'Physics', name: 'Momentum', formula: 'p = mv', note: 'Mass × velocity' },
  { category: 'Physics', name: 'Impulse', formula: 'J = FΔt = Δp', note: 'Change in momentum' },
  { category: 'Physics', name: 'Weight', formula: 'W = mg', note: 'g = 9.8 m/s²' },
  { category: 'Physics', name: 'Kinetic Energy', formula: 'KE = ½mv²', note: 'Energy of motion' },
  { category: 'Physics', name: 'Potential Energy', formula: 'PE = mgh', note: 'Gravitational PE' },
  { category: 'Physics', name: 'Work Done', formula: 'W = F·d·cosθ', note: 'θ = angle between F and d' },
  { category: 'Physics', name: 'Power', formula: 'P = W/t = F·v', note: 'Rate of doing work' },
  { category: 'Physics', name: 'Centripetal Force', formula: 'F = mv²/r', note: 'Circular motion' },
  { category: 'Physics', name: 'Centripetal Acceleration', formula: 'a = v²/r = ω²r', note: 'Circular motion' },
  { category: 'Physics', name: 'Angular Velocity', formula: 'ω = 2πf = 2π/T', note: 'Radians per second' },
  { category: 'Physics', name: 'Projectile Range', formula: 'R = u²sin2θ/g', note: 'Max at θ=45°' },
  { category: 'Physics', name: 'Projectile Max Height', formula: 'H = u²sin²θ/2g', note: 'Vertical motion' },
  { category: 'Physics', name: 'Projectile Time of Flight', formula: 'T = 2u sinθ/g', note: 'Total flight time' },
  { category: 'Physics', name: 'Friction', formula: 'f = μN', note: 'μ = coefficient, N = normal force' },
  { category: 'Physics', name: 'Pressure', formula: 'P = F/A', note: 'Force per unit area' },
  { category: 'Physics', name: 'Archimedes Principle', formula: 'F_buoyant = ρVg', note: 'ρ=fluid density, V=displaced volume' },
  { category: 'Physics', name: 'Density', formula: 'ρ = m/V', note: 'Mass per unit volume' },
  { category: 'Physics', name: 'Pascal\'s Law', formula: 'P = F/A (same at all points)', note: 'Hydraulic systems' },

  // ===== PHYSICS — HEAT & THERMODYNAMICS =====
  { category: 'Physics', name: 'Heat', formula: 'Q = mcΔT', note: 'Specific heat capacity' },
  { category: 'Physics', name: 'Latent Heat', formula: 'Q = mL', note: 'L = latent heat' },
  { category: 'Physics', name: 'Thermal Expansion', formula: 'ΔL = αLΔT', note: 'Linear expansion' },
  { category: 'Physics', name: 'Ideal Gas Law', formula: 'PV = nRT', note: 'R = 8.314 J/mol·K' },
  { category: 'Physics', name: 'Boyle\'s Law', formula: 'P₁V₁ = P₂V₂', note: 'T constant' },
  { category: 'Physics', name: 'Charles\' Law', formula: 'V₁/T₁ = V₂/T₂', note: 'P constant' },
  { category: 'Physics', name: 'Efficiency', formula: 'η = (useful output/input) × 100%', note: 'Machine efficiency' },

  // ===== PHYSICS — WAVES & OPTICS =====
  { category: 'Physics', name: 'Wave Speed', formula: 'v = fλ', note: 'v = frequency × wavelength' },
  { category: 'Physics', name: 'Frequency', formula: 'f = 1/T', note: 'T = time period' },
  { category: 'Physics', name: 'Doppler Effect', formula: 'f\' = f(v±v₀)/(v∓vₛ)', note: 'Moving source/observer' },
  { category: 'Physics', name: 'Mirror Formula', formula: '1/f = 1/v + 1/u', note: 'f=focal, v=image, u=object' },
  { category: 'Physics', name: 'Lens Formula', formula: '1/f = 1/v - 1/u', note: 'Sign convention' },
  { category: 'Physics', name: 'Magnification', formula: 'm = -v/u = h\'/h', note: 'Image/object height ratio' },
  { category: 'Physics', name: 'Refractive Index', formula: 'n = c/v = sin i/sin r', note: 'Snell\'s law' },
  { category: 'Physics', name: 'Critical Angle', formula: 'sin θc = 1/n', note: 'Total internal reflection' },
  { category: 'Physics', name: 'Power of Lens', formula: 'P = 1/f (diopters)', note: 'f in metres' },
  { category: 'Physics', name: 'Simple Pendulum', formula: 'T = 2π√(L/g)', note: 'Time period' },
  { category: 'Physics', name: 'Spring (SHM)', formula: 'T = 2π√(m/k)', note: 'k = spring constant' },

  // ===== PHYSICS — ELECTRICITY & MAGNETISM =====
  { category: 'Physics', name: 'Ohm\'s Law', formula: 'V = IR', note: 'Voltage = Current × Resistance' },
  { category: 'Physics', name: 'Resistance', formula: 'R = ρL/A', note: 'ρ=resistivity, L=length, A=area' },
  { category: 'Physics', name: 'Series Resistance', formula: 'R = R₁+R₂+R₃+...', note: 'Resistors in series' },
  { category: 'Physics', name: 'Parallel Resistance', formula: '1/R = 1/R₁+1/R₂+...', note: 'Resistors in parallel' },
  { category: 'Physics', name: 'Electrical Power', formula: 'P = VI = I²R = V²/R', note: 'Power formulas' },
  { category: 'Physics', name: 'Electrical Energy', formula: 'E = Pt = VIt', note: 'Energy consumed' },
  { category: 'Physics', name: 'Coulomb\'s Law', formula: 'F = kq₁q₂/r²', note: 'k = 9×10⁹ N·m²/C²' },
  { category: 'Physics', name: 'Electric Field', formula: 'E = F/q = kQ/r²', note: 'Field intensity' },
  { category: 'Physics', name: 'Capacitance', formula: 'C = Q/V', note: 'Charge/potential difference' },
  { category: 'Physics', name: 'Parallel Plate Capacitor', formula: 'C = ε₀A/d', note: 'A=area, d=separation' },
  { category: 'Physics', name: 'Magnetic Force', formula: 'F = BIL sinθ', note: 'On current-carrying wire' },
  { category: 'Physics', name: 'Faraday\'s Law', formula: 'ε = -dΦ/dt', note: 'Electromagnetic induction' },
  { category: 'Physics', name: 'Transformer', formula: 'Vₛ/Vₚ = Nₛ/Nₚ', note: 'Voltage ratio = turns ratio' },

  // ===== PHYSICS — MODERN =====
  { category: 'Physics', name: 'Einstein Mass-Energy', formula: 'E = mc²', note: 'c = 3×10⁸ m/s' },
  { category: 'Physics', name: 'Photoelectric Effect', formula: 'KE_max = hf - φ', note: 'h=Planck\'s constant, φ=work function' },
  { category: 'Physics', name: 'de Broglie Wavelength', formula: 'λ = h/p = h/mv', note: 'Matter waves' },

  // ===== CHEMISTRY =====
  { category: 'Chemistry', name: 'Moles', formula: 'n = m/M = N/Nₐ', note: 'm=mass, M=molar mass, N=particles' },
  { category: 'Chemistry', name: 'Molarity', formula: 'M = n/V (mol/L)', note: 'Concentration' },
  { category: 'Chemistry', name: 'Molality', formula: 'm = n/mass of solvent (kg)', note: 'mol/kg' },
  { category: 'Chemistry', name: 'Normality', formula: 'N = n × valency / V', note: 'Equivalent concentration' },
  { category: 'Chemistry', name: 'Dilution', formula: 'M₁V₁ = M₂V₂', note: 'Before and after dilution' },
  { category: 'Chemistry', name: 'Ideal Gas', formula: 'PV = nRT', note: 'Gas equation' },
  { category: 'Chemistry', name: 'Avogadro\'s Number', formula: 'Nₐ = 6.022 × 10²³ mol⁻¹', note: 'Particles per mole' },
  { category: 'Chemistry', name: 'pH', formula: 'pH = -log[H⁺]', note: 'Acidity measure' },
  { category: 'Chemistry', name: 'pOH', formula: 'pOH = -log[OH⁻]', note: 'Basicity measure' },
  { category: 'Chemistry', name: 'pH + pOH', formula: 'pH + pOH = 14', note: 'At 25°C' },
  { category: 'Chemistry', name: 'Percentage Composition', formula: '% = (mass of element/molar mass) × 100', note: 'In compound' },
  { category: 'Chemistry', name: 'Empirical Formula', formula: 'Simplest whole number ratio of atoms', note: 'From % composition' },
  { category: 'Chemistry', name: 'Faraday\'s Law (electrolysis)', formula: 'm = (EIt)/(96500)', note: 'E = equivalent weight' },
  { category: 'Chemistry', name: 'Rate of Reaction', formula: 'Rate = Δ[conc]/Δt', note: 'Change in concentration per time' },
  { category: 'Chemistry', name: 'Arrhenius Equation', formula: 'k = Ae^(-Ea/RT)', note: 'Temperature dependence of rate' },
  { category: 'Chemistry', name: 'Raoult\'s Law', formula: 'P = P° × mole fraction', note: 'Vapour pressure lowering' },
  { category: 'Chemistry', name: 'Oxidation Number', formula: 'Sum = charge on ion/molecule', note: 'Conservation in reactions' },

  // ===== BIOLOGY =====
  { category: 'Biology', name: 'Photosynthesis', formula: '6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂', note: 'In presence of sunlight & chlorophyll' },
  { category: 'Biology', name: 'Respiration', formula: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + Energy', note: 'Cellular respiration' },
  { category: 'Biology', name: 'Blood Groups', formula: 'A, B, AB, O — Rh+ or Rh-', note: '4 main groups' },
  { category: 'Biology', name: 'Mendel\'s Law', formula: 'F₂ ratio = 3:1 (monohybrid)', note: 'Dominant:Recessive phenotype' },

  // ===== MORE ALGEBRA =====
  { category: 'Algebra', name: 'Set Union', formula: 'n(A∪B) = n(A) + n(B) - n(A∩B)', note: 'Inclusion-exclusion principle' },
  { category: 'Algebra', name: 'Set (3 sets)', formula: 'n(A∪B∪C) = n(A)+n(B)+n(C) - n(A∩B) - n(B∩C) - n(C∩A) + n(A∩B∩C)', note: 'Three set formula' },
  { category: 'Algebra', name: 'De Morgan\'s Law', formula: '(A∪B)\' = A\'∩B\' and (A∩B)\' = A\'∪B\'', note: 'Set complement rules' },
  { category: 'Algebra', name: 'Identity (a+b)²', formula: 'a² + 2ab + b²', note: 'Perfect square expansion' },
  { category: 'Algebra', name: 'Identity (a-b)²', formula: 'a² - 2ab + b²', note: 'Perfect square expansion' },
  { category: 'Algebra', name: 'Identity (a+b)(a-b)', formula: 'a² - b²', note: 'Difference of squares' },
  { category: 'Algebra', name: 'Identity (a+b)³', formula: 'a³ + 3a²b + 3ab² + b³', note: 'Cube expansion' },
  { category: 'Algebra', name: 'Identity (a-b)³', formula: 'a³ - 3a²b + 3ab² - b³', note: 'Cube expansion' },
  { category: 'Algebra', name: 'a³+b³', formula: '(a+b)(a² - ab + b²)', note: 'Sum of cubes factorization' },
  { category: 'Algebra', name: 'a³-b³', formula: '(a-b)(a² + ab + b²)', note: 'Difference of cubes factorization' },
  { category: 'Algebra', name: 'Middle term (Binomial)', formula: 'T_{r+1} = ⁿCᵣ aⁿ⁻ʳ bʳ', note: 'General term in binomial expansion' },
  { category: 'Algebra', name: 'Middle term index', formula: 'Middle term at r = n/2 (n even) or (n+1)/2 (n odd)', note: 'Binomial expansion' },
  { category: 'Algebra', name: 'Sum of GP (r=1)', formula: 'Sₙ = na', note: 'When common ratio equals 1' },
  { category: 'Algebra', name: 'Insert n AMs', formula: 'd = (b-a)/(n+1)', note: 'Between a and b' },
  { category: 'Algebra', name: 'Complex conjugate', formula: 'z̄ = a - ib, z·z̄ = a²+b²', note: 'z = a + ib' },
  { category: 'Algebra', name: 'Modulus-Argument form', formula: 'z = r(cosθ + i sinθ)', note: 'r = |z|, θ = arg(z)' },
  { category: 'Algebra', name: 'Binary to Decimal', formula: 'Multiply each digit by 2^position and sum', note: 'Base conversion' },
  { category: 'Algebra', name: 'Decimal to Binary', formula: 'Repeated division by 2, read remainders bottom-up', note: 'Base conversion' },
  { category: 'Algebra', name: 'Inequality |x| < a', formula: '-a < x < a', note: 'a > 0' },
  { category: 'Algebra', name: 'Inequality |x| > a', formula: 'x < -a or x > a', note: 'a > 0' },
  { category: 'Algebra', name: 'Logarithm definition', formula: 'logₐb = x ⟺ aˣ = b', note: 'a > 0, a ≠ 1, b > 0' },
  { category: 'Algebra', name: 'logₐ1', formula: 'logₐ1 = 0', note: 'Logarithm of unity' },
  { category: 'Algebra', name: 'logₐa', formula: 'logₐa = 1', note: 'Logarithm of base' },
  { category: 'Algebra', name: 'a⁰', formula: 'a⁰ = 1 (a ≠ 0)', note: 'Zero exponent rule' },
  { category: 'Algebra', name: 'a⁻ⁿ', formula: 'a⁻ⁿ = 1/aⁿ', note: 'Negative exponent' },
  { category: 'Algebra', name: 'a^(m/n)', formula: 'ⁿ√(aᵐ)', note: 'Fractional exponent' },

  // ===== MORE TRIGONOMETRY =====
  { category: 'Trigonometry', name: 'tan(A-B)', formula: 'tan(A-B) = (tanA - tanB)/(1 + tanA·tanB)', note: 'Subtraction formula' },
  { category: 'Trigonometry', name: 'cot(A+B)', formula: 'cot(A+B) = (cotA·cotB - 1)/(cotB + cotA)', note: 'Addition formula' },
  { category: 'Trigonometry', name: 'sin²θ', formula: 'sin²θ = (1 - cos2θ)/2', note: 'Power reduction' },
  { category: 'Trigonometry', name: 'cos²θ', formula: 'cos²θ = (1 + cos2θ)/2', note: 'Power reduction' },
  { category: 'Trigonometry', name: 'tan 3θ', formula: 'tan 3θ = (3tanθ - tan³θ)/(1 - 3tan²θ)', note: 'Triple angle' },
  { category: 'Trigonometry', name: 'cos A - cos B', formula: '2 sin((A+B)/2) sin((B-A)/2)', note: 'Difference to product' },
  { category: 'Trigonometry', name: 'cos A · cos B', formula: '½[cos(A+B) + cos(A-B)]', note: 'Product to sum' },
  { category: 'Trigonometry', name: 'sin A · sin B', formula: '½[cos(A-B) - cos(A+B)]', note: 'Product to sum' },
  { category: 'Trigonometry', name: 'General Solution tanθ', formula: 'θ = nπ + α', note: 'tanθ = tanα' },
  { category: 'Trigonometry', name: 'sin 0°', formula: '0', note: 'Standard value' },
  { category: 'Trigonometry', name: 'sin 30°', formula: '1/2', note: 'Standard value' },
  { category: 'Trigonometry', name: 'sin 45°', formula: '1/√2', note: 'Standard value' },
  { category: 'Trigonometry', name: 'sin 60°', formula: '√3/2', note: 'Standard value' },
  { category: 'Trigonometry', name: 'sin 90°', formula: '1', note: 'Standard value' },
  { category: 'Trigonometry', name: 'cos 0°', formula: '1', note: 'Standard value' },
  { category: 'Trigonometry', name: 'cos 30°', formula: '√3/2', note: 'Standard value' },
  { category: 'Trigonometry', name: 'cos 45°', formula: '1/√2', note: 'Standard value' },
  { category: 'Trigonometry', name: 'cos 60°', formula: '1/2', note: 'Standard value' },
  { category: 'Trigonometry', name: 'tan 30°', formula: '1/√3', note: 'Standard value' },
  { category: 'Trigonometry', name: 'tan 60°', formula: '√3', note: 'Standard value' },
  { category: 'Trigonometry', name: 'cosecθ', formula: 'cosecθ = 1/sinθ', note: 'Reciprocal ratio' },
  { category: 'Trigonometry', name: 'secθ', formula: 'secθ = 1/cosθ', note: 'Reciprocal ratio' },
  { category: 'Trigonometry', name: 'cotθ', formula: 'cotθ = 1/tanθ = cosθ/sinθ', note: 'Reciprocal ratio' },
  { category: 'Trigonometry', name: 'Angle of Depression', formula: 'h = d·tanθ', note: 'θ below horizontal' },
  { category: 'Trigonometry', name: 'Area of triangle (2 sides)', formula: 'A = ½ab sinC', note: 'SAS formula' },
  { category: 'Trigonometry', name: 'Sine Rule', formula: 'a/sinA = b/sinB = c/sinC = 2R', note: 'R = circumradius' },
  { category: 'Trigonometry', name: 'Cosine Rule', formula: 'c² = a² + b² - 2ab cosC', note: 'General triangle' },

  // ===== MORE COORDINATE GEOMETRY =====
  { category: 'Coordinate Geometry', name: 'External Division', formula: '((mx₂-nx₁)/(m-n), (my₂-ny₁)/(m-n))', note: 'Ratio m:n externally' },
  { category: 'Coordinate Geometry', name: 'Area of triangle (determinant)', formula: 'A = ½|x₁(y₂-y₃)+x₂(y₃-y₁)+x₃(y₁-y₂)|', note: 'Coordinate geometry' },
  { category: 'Coordinate Geometry', name: 'Centroid', formula: 'G = ((x₁+x₂+x₃)/3, (y₁+y₂+y₃)/3)', note: 'Triangle centroid' },
  { category: 'Coordinate Geometry', name: 'Perpendicular distance (origin)', formula: 'd = |c|/√(a²+b²)', note: 'Line ax+by+c=0' },
  { category: 'Coordinate Geometry', name: 'Family of lines', formula: 'L₁ + λL₂ = 0', note: 'Lines through intersection' },
  { category: 'Coordinate Geometry', name: 'Pair of lines', formula: 'ax² + 2hxy + by² = 0', note: 'Homogeneous equation' },
  { category: 'Coordinate Geometry', name: 'Angle between pair of lines', formula: 'tanθ = ±2√(h²-ab)/(a+b)', note: 'From ax²+2hxy+by²=0' },
  { category: 'Coordinate Geometry', name: 'Tangent to circle', formula: 'T = 0: xx₁+yy₁ = r²', note: 'At point (x₁,y₁) on circle' },
  { category: 'Coordinate Geometry', name: 'Length of tangent', formula: 'L = √(S₁) where S₁ = x₁²+y₁²+2gx₁+2fy₁+c', note: 'From external point' },
  { category: 'Coordinate Geometry', name: 'Parabola (x²=4ay)', formula: 'Focus (0,a), directrix y = -a', note: 'Vertical parabola' },
  { category: 'Coordinate Geometry', name: 'Parabola parametric', formula: 'x = at², y = 2at', note: 'y² = 4ax' },
  { category: 'Coordinate Geometry', name: 'Ellipse parametric', formula: 'x = a cosθ, y = b sinθ', note: 'x²/a² + y²/b² = 1' },
  { category: 'Coordinate Geometry', name: 'Ellipse foci', formula: 'Foci at (±ae, 0), directrices x = ±a/e', note: 'Standard ellipse' },
  { category: 'Coordinate Geometry', name: 'Hyperbola foci', formula: 'Foci at (±ae, 0), e > 1', note: 'Standard hyperbola' },
  { category: 'Coordinate Geometry', name: 'Rectangular hyperbola', formula: 'xy = c²', note: 'Asymptotes: x=0, y=0' },
  { category: 'Coordinate Geometry', name: 'Polar coordinates', formula: 'x = r cosθ, y = r sinθ', note: 'Conversion from polar' },
  { category: 'Coordinate Geometry', name: 'r (polar)', formula: 'r = √(x²+y²)', note: 'Polar radius' },
  { category: 'Coordinate Geometry', name: 'Section formula (3D)', formula: '((mx₂+nx₁)/(m+n), (my₂+ny₁)/(m+n), (mz₂+nz₁)/(m+n))', note: '3D internal division' },
  { category: 'Coordinate Geometry', name: 'Direction ratios', formula: 'a:b:c proportional to direction cosines', note: 'l/a = m/b = n/c' },
  { category: 'Coordinate Geometry', name: 'Angle between lines (3D)', formula: 'cosθ = (a₁a₂+b₁b₂+c₁c₂)/(√(a₁²+b₁²+c₁²)·√(a₂²+b₂²+c₂²))', note: 'Direction ratios' },
  { category: 'Coordinate Geometry', name: 'Distance point to plane', formula: 'd = |ax₁+by₁+cz₁+d|/√(a²+b²+c²)', note: 'Plane ax+by+cz+d=0' },
  { category: 'Coordinate Geometry', name: 'Line in 3D (vector)', formula: 'r = a + λb', note: 'a = point, b = direction vector' },

  // ===== MORE CALCULUS =====
  { category: 'Calculus', name: 'd/dx(sec x)', formula: 'sec x tan x', note: 'Trig derivative' },
  { category: 'Calculus', name: 'd/dx(cosec x)', formula: '-cosec x cot x', note: 'Trig derivative' },
  { category: 'Calculus', name: 'd/dx(cot x)', formula: '-cosec²x', note: 'Trig derivative' },
  { category: 'Calculus', name: 'd/dx(sin⁻¹x)', formula: '1/√(1-x²)', note: 'Inverse trig derivative' },
  { category: 'Calculus', name: 'd/dx(cos⁻¹x)', formula: '-1/√(1-x²)', note: 'Inverse trig derivative' },
  { category: 'Calculus', name: 'd/dx(tan⁻¹x)', formula: '1/(1+x²)', note: 'Inverse trig derivative' },
  { category: 'Calculus', name: 'd/dx(log x)', formula: '1/(x ln a)', note: 'General logarithm' },
  { category: 'Calculus', name: 'Implicit differentiation', formula: 'Differentiate both sides w.r.t. x', note: 'For implicit equations' },
  { category: 'Calculus', name: 'Parametric derivative', formula: 'dy/dx = (dy/dt)/(dx/dt)', note: 'Parametric curves' },
  { category: 'Calculus', name: '∫sec²x dx', formula: 'tan x + C', note: 'Standard integral' },
  { category: 'Calculus', name: '∫cosec²x dx', formula: '-cot x + C', note: 'Standard integral' },
  { category: 'Calculus', name: '∫sec x tan x dx', formula: 'sec x + C', note: 'Standard integral' },
  { category: 'Calculus', name: '∫1/(1+x²) dx', formula: 'tan⁻¹x + C', note: 'Standard integral' },
  { category: 'Calculus', name: '∫1/√(1-x²) dx', formula: 'sin⁻¹x + C', note: 'Standard integral' },
  { category: 'Calculus', name: '∫aˣ dx', formula: 'aˣ/(ln a) + C', note: 'Exponential integral' },
  { category: 'Calculus', name: '∫(f\'/f) dx', formula: 'ln|f| + C', note: 'Logarithmic form' },
  { category: 'Calculus', name: 'Area between curves', formula: 'A = ∫ₐᵇ (y₁ - y₂) dx', note: 'y₁ ≥ y₂' },
  { category: 'Calculus', name: 'Volume of revolution', formula: 'V = π∫ₐᵇ y² dx', note: 'About x-axis' },
  { category: 'Calculus', name: 'Rolle\'s Theorem', formula: 'f(a)=f(b) → ∃c: f\'(c)=0', note: 'a < c < b' },
  { category: 'Calculus', name: 'Mean Value Theorem', formula: 'f\'(c) = [f(b)-f(a)]/(b-a)', note: 'a < c < b' },
  { category: 'Calculus', name: 'lim(x→0) tanx/x', formula: '1', note: 'Standard limit' },
  { category: 'Calculus', name: 'lim(x→0) (aˣ-1)/x', formula: 'ln a', note: 'Standard limit' },
  { category: 'Calculus', name: 'lim(x→∞) (1+x/n)ⁿ', formula: 'eˣ', note: 'Exponential limit' },

  // ===== DIFFERENTIAL EQUATIONS =====
  { category: 'Differential Equations', name: 'Order', formula: 'Highest derivative in the equation', note: 'DE classification' },
  { category: 'Differential Equations', name: 'Degree', formula: 'Power of highest order derivative', note: 'After clearing fractions' },
  { category: 'Differential Equations', name: 'Variable separable', formula: '∫f(y)dy = ∫g(x)dx', note: 'dy/dx = f(x)g(y)' },
  { category: 'Differential Equations', name: 'Homogeneous DE', formula: 'Substitute y = vx, dy/dx = v + x(dv/dx)', note: 'dy/dx = f(y/x)' },
  { category: 'Differential Equations', name: 'Linear DE (1st order)', formula: 'dy/dx + Py = Q', note: 'IF = e^∫P dx' },
  { category: 'Differential Equations', name: 'Integrating Factor', formula: 'IF = e^∫P(x)dx', note: 'For linear first order DE' },
  { category: 'Differential Equations', name: 'General solution', formula: 'y = IF·∫(Q·IF)dx + C/IF', note: 'Linear first order DE' },
  { category: 'Differential Equations', name: 'dy/dx = ky', formula: 'y = Ce^(kx)', note: 'Exponential growth/decay' },

  // ===== MORE MATRICES =====
  { category: 'Matrices', name: 'Determinant 3×3', formula: '|A| = a(ei-fh) - b(di-fg) + c(dh-eg)', note: 'Sarrus rule expansion' },
  { category: 'Matrices', name: 'Singular matrix', formula: '|A| = 0', note: 'No inverse exists' },
  { category: 'Matrices', name: 'Non-singular matrix', formula: '|A| ≠ 0', note: 'Inverse exists' },
  { category: 'Matrices', name: 'Transpose property', formula: '(AB)ᵀ = BᵀAᵀ', note: 'Matrix transpose' },
  { category: 'Matrices', name: 'Identity matrix', formula: 'AI = IA = A', note: 'Multiplicative identity' },
  { category: 'Matrices', name: 'Trace', formula: 'tr(A) = sum of diagonal elements', note: 'Square matrix property' },
  { category: 'Matrices', name: 'Symmetric matrix', formula: 'Aᵀ = A', note: 'Matrix equals its transpose' },
  { category: 'Matrices', name: 'Skew-symmetric', formula: 'Aᵀ = -A, diagonal elements = 0', note: 'Anti-symmetric matrix' },

  // ===== MORE VECTORS =====
  { category: 'Vectors', name: 'Parallelogram Law', formula: '|a+b|² = |a|² + |b|² + 2a·b', note: 'Vector addition' },
  { category: 'Vectors', name: 'Cross product (components)', formula: 'a×b = (a₂b₃-a₃b₂, a₃b₁-a₁b₃, a₁b₂-a₂b₁)', note: 'Determinant form' },
  { category: 'Vectors', name: 'Scalar triple product', formula: 'a·(b×c) = volume of parallelepiped', note: 'Geometric meaning' },
  { category: 'Vectors', name: 'Vector triple product', formula: 'a×(b×c) = b(a·c) - c(a·b)', note: 'BAC-CAB rule' },
  { category: 'Vectors', name: 'Torque', formula: 'τ = r × F', note: 'Moment of force' },
  { category: 'Vectors', name: 'Area of parallelogram', formula: 'A = |a × b|', note: 'Vector cross product' },

  // ===== MORE STATISTICS =====
  { category: 'Statistics', name: 'Mean (grouped)', formula: 'x̄ = Σfᵢxᵢ/Σfᵢ', note: 'Frequency distribution' },
  { category: 'Statistics', name: 'Median (grouped)', formula: 'L + [(N/2 - cf)/f] × h', note: 'L=lower boundary, cf=cumulative freq, h=width' },
  { category: 'Statistics', name: 'Mode (grouped)', formula: 'L + [(f₁-f₀)/(2f₁-f₀-f₂)] × h', note: 'Modal class formula' },
  { category: 'Statistics', name: 'Variance (shortcut)', formula: 'σ² = (Σxᵢ²/n) - x̄²', note: 'Computational formula' },
  { category: 'Statistics', name: 'Mean deviation', formula: 'MD = Σ|xᵢ - x̄|/n', note: 'Average absolute deviation' },
  { category: 'Statistics', name: 'Quartiles', formula: 'Q₁ at N/4, Q₂ = median, Q₃ at 3N/4', note: 'Positional measures' },
  { category: 'Statistics', name: 'Range', formula: 'Range = max - min', note: 'Simplest dispersion measure' },
  { category: 'Statistics', name: 'Correlation (r)', formula: 'r = Σ(xᵢ-x̄)(yᵢ-ȳ)/√[Σ(xᵢ-x̄)²·Σ(yᵢ-ȳ)²]', note: '-1 ≤ r ≤ 1' },

  // ===== MORE PROBABILITY =====
  { category: 'Probability', name: 'Mutually exclusive', formula: 'P(A∩B) = 0, P(A∪B) = P(A)+P(B)', note: 'Cannot occur together' },
  { category: 'Probability', name: 'Exhaustive events', formula: 'P(A₁∪A₂∪...∪Aₙ) = 1', note: 'Cover all outcomes' },
  { category: 'Probability', name: 'Mean (binomial)', formula: 'μ = np', note: 'Binomial distribution' },
  { category: 'Probability', name: 'Variance (binomial)', formula: 'σ² = np(1-p)', note: 'Binomial distribution' },
  { category: 'Probability', name: 'Expected value', formula: 'E(X) = Σxᵢ·P(xᵢ)', note: 'Mean of random variable' },
  { category: 'Probability', name: 'Cards — total', formula: '52 cards, 4 suits, 13 ranks each', note: 'Standard deck' },
  { category: 'Probability', name: 'Dice — total outcomes', formula: '6 outcomes per die, n dice = 6ⁿ', note: 'Equally likely' },

  // ===== MORE PHYSICS =====
  { category: 'Physics', name: 'Average velocity', formula: 'v_avg = total displacement/total time', note: 'Vector quantity' },
  { category: 'Physics', name: 'Average speed', formula: 's_avg = total distance/total time', note: 'Scalar quantity' },
  { category: 'Physics', name: 'Relative velocity', formula: 'v_AB = v_A - v_B', note: 'A relative to B' },
  { category: 'Physics', name: 'Banking of roads', formula: 'tanθ = v²/rg', note: 'θ = banking angle' },
  { category: 'Physics', name: 'Conservation of momentum', formula: 'm₁u₁ + m₂u₂ = m₁v₁ + m₂v₂', note: 'Collision (no external force)' },
  { category: 'Physics', name: 'Elastic collision', formula: 'KE before = KE after', note: 'Kinetic energy conserved' },
  { category: 'Physics', name: 'Coefficient of restitution', formula: 'e = (v₂-v₁)/(u₁-u₂)', note: '0 ≤ e ≤ 1' },
  { category: 'Physics', name: 'Torque', formula: 'τ = r × F = rF sinθ', note: 'Rotational effect of force' },
  { category: 'Physics', name: 'Moment of inertia (point mass)', formula: 'I = mr²', note: 'About axis at distance r' },
  { category: 'Physics', name: 'Angular momentum', formula: 'L = Iω = mvr', note: 'Rotational analogue of momentum' },
  { category: 'Physics', name: 'Rotational KE', formula: 'KE = ½Iω²', note: 'Energy of rotation' },
  { category: 'Physics', name: 'Gravitational force', formula: 'F = Gm₁m₂/r²', note: 'G = 6.67×10⁻¹¹ N·m²/kg²' },
  { category: 'Physics', name: 'Gravitational field', formula: 'g = GM/r²', note: 'Acceleration due to gravity' },
  { category: 'Physics', name: 'Escape velocity', formula: 'v_e = √(2GM/R)', note: 'Minimum speed to leave planet' },
  { category: 'Physics', name: 'Orbital velocity', formula: 'v = √(GM/r)', note: 'Satellite orbit' },
  { category: 'Physics', name: 'Kepler\'s 3rd Law', formula: 'T² ∝ r³', note: 'Planetary motion' },
  { category: 'Physics', name: 'Elastic potential energy', formula: 'PE = ½kx²', note: 'Spring energy' },
  { category: 'Physics', name: 'Hooke\'s Law', formula: 'F = -kx', note: 'Spring force' },
  { category: 'Physics', name: 'Conservation of energy', formula: 'KE + PE = constant', note: 'No non-conservative forces' },
  { category: 'Physics', name: 'Stress', formula: 'σ = F/A', note: 'Force per unit area (material)' },
  { category: 'Physics', name: 'Strain', formula: 'ε = ΔL/L', note: 'Deformation ratio' },
  { category: 'Physics', name: 'Young\'s modulus', formula: 'Y = stress/strain = FL/(AΔL)', note: 'Elastic property' },
  { category: 'Physics', name: 'Viscosity (Stokes)', formula: 'F = 6πηrv', note: 'Sphere in viscous fluid' },
  { category: 'Physics', name: 'Terminal velocity', formula: 'v = 2r²(ρ-σ)g/(9η)', note: 'Falling sphere in fluid' },
  { category: 'Physics', name: 'Surface tension', formula: 'S = F/L', note: 'Force per unit length' },
  { category: 'Physics', name: 'Capillary rise', formula: 'h = 2S cosθ/(rρg)', note: 'Liquid in narrow tube' },
  { category: 'Physics', name: 'Bernoulli\'s equation', formula: 'P + ½ρv² + ρgh = constant', note: 'Fluid dynamics' },
  { category: 'Physics', name: 'Continuity equation', formula: 'A₁v₁ = A₂v₂', note: 'Incompressible fluid flow' },
  { category: 'Physics', name: 'Gay-Lussac\'s Law', formula: 'P₁/T₁ = P₂/T₂', note: 'V constant' },
  { category: 'Physics', name: 'Combined gas law', formula: 'P₁V₁/T₁ = P₂V₂/T₂', note: 'Ideal gas' },
  { category: 'Physics', name: 'First law of thermodynamics', formula: 'ΔU = Q - W', note: 'Energy conservation' },
  { category: 'Physics', name: 'Carnot efficiency', formula: 'η = 1 - T₂/T₁', note: 'Maximum possible efficiency' },
  { category: 'Physics', name: 'Linear expansion (area)', formula: 'ΔA = 2αAΔT', note: 'Area expansion' },
  { category: 'Physics', name: 'Linear expansion (volume)', formula: 'ΔV = 3αVΔT', note: 'Volume expansion' },
  { category: 'Physics', name: 'Thermal conductivity', formula: 'Q/t = kAΔT/L', note: 'Heat conduction rate' },
  { category: 'Physics', name: 'Stefan-Boltzmann law', formula: 'P = εσAT⁴', note: 'Radiation power' },
  { category: 'Physics', name: 'Newton\'s law of cooling', formula: 'dT/dt = -k(T-T₀)', note: 'Rate of cooling' },
  { category: 'Physics', name: 'Beat frequency', formula: 'f_beat = |f₁ - f₂|', note: 'Interference of sound' },
  { category: 'Physics', name: 'Open pipe frequency', formula: 'f = nv/(2L)', note: 'n = 1,2,3... harmonics' },
  { category: 'Physics', name: 'Closed pipe frequency', formula: 'f = nv/(4L)', note: 'n = 1,3,5... odd harmonics' },
  { category: 'Physics', name: 'Resonance', formula: 'Occurs when driving frequency = natural frequency', note: 'Maximum amplitude' },
  { category: 'Physics', name: 'Intensity of sound', formula: 'I = P/A', note: 'Power per unit area' },
  { category: 'Physics', name: 'Decibel scale', formula: 'β = 10 log(I/I₀)', note: 'Sound level' },
  { category: 'Physics', name: 'Lens maker\'s formula', formula: '1/f = (n-1)(1/R₁ - 1/R₂)', note: 'n = refractive index' },
  { category: 'Physics', name: 'Prism deviation', formula: 'δ = (n-1)A', note: 'Small angle approximation' },
  { category: 'Physics', name: 'Dispersion', formula: 'n varies with wavelength', note: 'Violet bends more than red' },
  { category: 'Physics', name: 'Young\'s double slit', formula: 'y = nλD/d', note: 'Fringe position' },
  { category: 'Physics', name: 'Fringe width', formula: 'β = λD/d', note: 'Distance between bright fringes' },
  { category: 'Physics', name: 'Electric potential', formula: 'V = kQ/r', note: 'Potential at distance r' },
  { category: 'Physics', name: 'Potential difference', formula: 'V = W/q', note: 'Work per unit charge' },
  { category: 'Physics', name: 'Capacitors in series', formula: '1/C = 1/C₁ + 1/C₂ + ...', note: 'Series combination' },
  { category: 'Physics', name: 'Capacitors in parallel', formula: 'C = C₁ + C₂ + ...', note: 'Parallel combination' },
  { category: 'Physics', name: 'Energy stored (capacitor)', formula: 'U = ½CV² = ½QV = Q²/2C', note: 'Electric field energy' },
  { category: 'Physics', name: 'Drift velocity', formula: 'v_d = I/(nAe)', note: 'n=electron density, A=area' },
  { category: 'Physics', name: 'Kirchhoff\'s Current Law', formula: 'ΣI_in = ΣI_out', note: 'Junction rule' },
  { category: 'Physics', name: 'Kirchhoff\'s Voltage Law', formula: 'ΣV = 0 around any closed loop', note: 'Loop rule' },
  { category: 'Physics', name: 'Wheatstone bridge', formula: 'P/Q = R/S when balanced', note: 'No current in galvanometer' },
  { category: 'Physics', name: 'Magnetic field (wire)', formula: 'B = μ₀I/(2πr)', note: 'Long straight conductor' },
  { category: 'Physics', name: 'Magnetic field (solenoid)', formula: 'B = μ₀nI', note: 'n = turns per unit length' },
  { category: 'Physics', name: 'Force on charge', formula: 'F = qvB sinθ', note: 'Lorentz force' },
  { category: 'Physics', name: 'Magnetic flux', formula: 'Φ = BA cosθ', note: 'Flux through surface' },
  { category: 'Physics', name: 'Self-inductance', formula: 'ε = -L(dI/dt)', note: 'Induced EMF' },
  { category: 'Physics', name: 'Energy (inductor)', formula: 'U = ½LI²', note: 'Magnetic field energy' },
  { category: 'Physics', name: 'AC voltage', formula: 'V = V₀ sin(ωt)', note: 'Sinusoidal AC' },
  { category: 'Physics', name: 'AC current', formula: 'I = I₀ sin(ωt)', note: 'Sinusoidal AC' },
  { category: 'Physics', name: 'RMS value', formula: 'V_rms = V₀/√2', note: 'Root mean square' },
  { category: 'Physics', name: 'Reactance (capacitor)', formula: 'X_C = 1/(ωC)', note: 'Capacitive reactance' },
  { category: 'Physics', name: 'Reactance (inductor)', formula: 'X_L = ωL', note: 'Inductive reactance' },
  { category: 'Physics', name: 'Impedance', formula: 'Z = √(R² + (X_L - X_C)²)', note: 'LCR circuit' },
  { category: 'Physics', name: 'Resonance (LCR)', formula: 'f₀ = 1/(2π√(LC))', note: 'Resonant frequency' },
  { category: 'Physics', name: 'Planck\'s constant', formula: 'h = 6.626 × 10⁻³⁴ J·s', note: 'Quantum constant' },
  { category: 'Physics', name: 'Photon energy', formula: 'E = hf = hc/λ', note: 'Energy of light quantum' },
  { category: 'Physics', name: 'Radioactive decay', formula: 'N = N₀e^(-λt)', note: 'λ = decay constant' },
  { category: 'Physics', name: 'Half-life', formula: 't₁/₂ = 0.693/λ', note: 'Time for half to decay' },

  // ===== MORE CHEMISTRY =====
  { category: 'Chemistry', name: 'Atomic mass unit', formula: '1 u = 1/12 mass of C-12 atom', note: 'Unified atomic mass' },
  { category: 'Chemistry', name: 'Equivalent weight', formula: 'EW = Molar mass/valency', note: 'Chemical equivalent' },
  { category: 'Chemistry', name: 'Mole fraction', formula: 'X_A = n_A/(n_A + n_B)', note: 'Ratio of moles' },
  { category: 'Chemistry', name: 'Mass percent', formula: 'Mass % = (mass of solute/mass of solution) × 100', note: 'Concentration' },
  { category: 'Chemistry', name: 'Parts per million', formula: 'ppm = (mass of solute/mass of solution) × 10⁶', note: 'Dilute solutions' },
  { category: 'Chemistry', name: 'Dalton\'s Law', formula: 'P_total = P₁ + P₂ + P₃ + ...', note: 'Partial pressures' },
  { category: 'Chemistry', name: 'Graham\'s Law', formula: 'r₁/r₂ = √(M₂/M₁)', note: 'Rate of diffusion' },
  { category: 'Chemistry', name: 'Henry\'s Law', formula: 'C = kP', note: 'Gas solubility in liquid' },
  { category: 'Chemistry', name: 'Van\'t Hoff factor', formula: 'i = observed particles/theoretical particles', note: 'Colligative properties' },
  { category: 'Chemistry', name: 'Boiling point elevation', formula: 'ΔT_b = K_b·m·i', note: 'Colligative property' },
  { category: 'Chemistry', name: 'Freezing point depression', formula: 'ΔT_f = K_f·m·i', note: 'Colligative property' },
  { category: 'Chemistry', name: 'Osmotic pressure', formula: 'π = MRT', note: 'Van\'t Hoff equation' },
  { category: 'Chemistry', name: 'Kw (water)', formula: 'Kw = [H⁺][OH⁻] = 10⁻¹⁴ at 25°C', note: 'Ion product of water' },
  { category: 'Chemistry', name: 'pKa', formula: 'pKa = -log Ka', note: 'Acid dissociation constant' },
  { category: 'Chemistry', name: 'Henderson-Hasselbalch', formula: 'pH = pKa + log([salt]/[acid])', note: 'Buffer solution' },
  { category: 'Chemistry', name: 'Nernst equation', formula: 'E = E° - (RT/nF)ln Q', note: 'Electrode potential' },
  { category: 'Chemistry', name: 'Electrochemical cell', formula: 'E°cell = E°cathode - E°anode', note: 'Cell EMF' },
  { category: 'Chemistry', name: 'ΔG (electrochemistry)', formula: 'ΔG = -nFE', note: 'Gibbs free energy' },
  { category: 'Chemistry', name: 'Rate law', formula: 'Rate = k[A]ᵐ[B]ⁿ', note: 'm,n = order w.r.t. each reactant' },
  { category: 'Chemistry', name: 'Half-life (1st order)', formula: 't₁/₂ = 0.693/k', note: 'First order reaction' },
  { category: 'Chemistry', name: 'Ideal gas density', formula: 'd = PM/RT', note: 'Gas density at STP' },
  { category: 'Chemistry', name: 'STP conditions', formula: '0°C (273 K), 1 atm pressure', note: 'Standard temperature and pressure' },
  { category: 'Chemistry', name: 'Molar volume at STP', formula: '22.4 L/mol', note: 'Ideal gas at STP' },
  { category: 'Chemistry', name: 'Combustion (hydrocarbon)', formula: 'CₙHₘ + O₂ → CO₂ + H₂O', note: 'Balance C then H then O' },
  { category: 'Chemistry', name: 'Valency (common)', formula: 'H=1, O=2, N=3, C=4, Na=1, Ca=2, Al=3, Cl=1', note: 'Common valencies' },

  // ===== MORE BIOLOGY =====
  { category: 'Biology', name: 'Cell theory', formula: 'All living things made of cells; cells from pre-existing cells', note: 'Fundamental biology' },
  { category: 'Biology', name: 'Mitosis result', formula: '1 cell → 2 identical diploid cells', note: 'Somatic cell division' },
  { category: 'Biology', name: 'Meiosis result', formula: '1 cell → 4 haploid gametes', note: 'Sexual reproduction' },
  { category: 'Biology', name: 'DNA structure', formula: 'Double helix, A-T (2 H-bonds), G-C (3 H-bonds)', note: 'Watson-Crick model' },
  { category: 'Biology', name: 'Central dogma', formula: 'DNA → RNA → Protein', note: 'Genetic information flow' },
  { category: 'Biology', name: 'Heart rate', formula: 'Normal resting: 60-100 beats/min', note: 'Adult human' },
  { category: 'Biology', name: 'Blood pressure', formula: 'Normal: 120/80 mmHg', note: 'Systolic/Diastolic' },
  { category: 'Biology', name: 'Human chromosomes', formula: '46 chromosomes (23 pairs)', note: 'Diploid number 2n=46' },
  { category: 'Biology', name: 'Calories (food)', formula: 'Carbohydrates & proteins: 4 kcal/g, Fats: 9 kcal/g', note: 'Energy values' },
  { category: 'Biology', name: 'Vitamins (water-soluble)', formula: 'B complex, C — not stored in body', note: 'Daily intake needed' },
  { category: 'Biology', name: 'Vitamins (fat-soluble)', formula: 'A, D, E, K — stored in liver/fat', note: 'Can accumulate to toxic levels' }
];
