const TRICK_CATEGORIES = [
  'All', 'Math Shortcuts', 'Trigonometry Tricks', 'Physics Tricks',
  'Chemistry Tricks', 'English Tricks', 'History Mnemonics', 'Geography Tricks',
  'Polity Tricks', 'Exam Hacks', 'Memory Tricks'
];

const TRICKS = [
  // ===== MATH SHORTCUTS =====
  { category: 'Math Shortcuts', title: 'Square of number ending in 5', trick: '25²: 2×3=6, append 25 → 625. 35²: 3×4=12, append 25 → 1225', example: 'n5² = n(n+1) followed by 25' },
  { category: 'Math Shortcuts', title: 'Multiply by 11 (2-digit)', trick: '36×11: 3_(3+6)_6 = 396. Add digits in middle.', example: '45×11 = 495' },
  { category: 'Math Shortcuts', title: 'Multiply by 5', trick: 'Divide by 2, then multiply by 10. 48×5 = 240', example: 'Any number × 5 = number/2 × 10' },
  { category: 'Math Shortcuts', title: 'Multiply by 25', trick: 'Divide by 4, multiply by 100. 84×25 = 2100', example: '×25 = ÷4 × 100' },
  { category: 'Math Shortcuts', title: 'Square of numbers 50-59', trick: '54²: 25+(4)=29, append 4²=16 → 2916', example: '5x² = (25+x) followed by x²' },
  { category: 'Math Shortcuts', title: 'Percentage Trick', trick: '15% of 80 = 80% of 15 = 12. Swap and calculate!', example: 'x% of y = y% of x' },
  { category: 'Math Shortcuts', title: 'Quick Percentage', trick: '10% = divide by 10. 1% = divide by 100. 5% = half of 10%.', example: '17% of 200 = 10% + 5% + 1% + 1% = 34' },
  { category: 'Math Shortcuts', title: 'Successive Discount', trick: '20% + 10% ≠ 30%. Actual = 100×0.8×0.9 = 72, i.e. 28% off', example: 'Multiply remaining percentages' },
  { category: 'Math Shortcuts', title: 'HCF by Division', trick: 'Divide larger by smaller, repeat with remainder until 0. Last divisor = HCF', example: 'HCF(48,18): 48=2×18+12, 18=1×12+6, 12=2×6+0 → HCF=6' },
  { category: 'Math Shortcuts', title: 'LCM Shortcut', trick: 'LCM = (a×b)/HCF(a,b)', example: 'LCM(12,18) = 216/6 = 36' },
  { category: 'Math Shortcuts', title: 'Sum of n natural numbers', trick: 'n(n+1)/2. For 1 to 100: 100×101/2 = 5050', example: 'Gauss formula' },
  { category: 'Math Shortcuts', title: 'Difference of Squares', trick: 'a²-b² = (a+b)(a-b). 97×103 = 100²-3² = 10000-9 = 9991', example: 'Use when numbers equidistant from round number' },
  { category: 'Math Shortcuts', title: 'Cube of 2-digit number', trick: 'Use (a+b)³ expansion or memorize cubes 1-30', example: '13³ = 2197, 23³ = 12167' },
  { category: 'Math Shortcuts', title: 'Divisibility by 3', trick: 'Sum of digits divisible by 3 → number divisible by 3', example: '12345: 1+2+3+4+5=15 ✓' },
  { category: 'Math Shortcuts', title: 'Divisibility by 9', trick: 'Sum of digits divisible by 9 → number divisible by 9', example: '123456789: sum=45 ✓' },
  { category: 'Math Shortcuts', title: 'Divisibility by 11', trick: 'Alternating sum of digits divisible by 11', example: '918082: (9+8+2)-(1+0+8)=9 ✓' },
  { category: 'Math Shortcuts', title: 'Unit Digit Pattern', trick: 'Powers cycle: 2→2,4,8,6 | 3→3,9,7,1 | 7→7,9,3,1 | 9→9,1', example: '7^100: 100÷4 remainder 0 → unit digit 1' },
  { category: 'Math Shortcuts', title: 'Quadratic by Inspection', trick: 'x²+5x+6: find two numbers that multiply to 6 and add to 5 → (x+2)(x+3)', example: 'Split middle term method' },
  { category: 'Math Shortcuts', title: 'AP/GP Quick Check', trick: 'AP: difference constant. GP: ratio constant. Check 2-3 terms only.', example: '2,5,8,11 → d=3, AP' },

  // ===== TRIGONOMETRY TRICKS =====
  { category: 'Trigonometry Tricks', title: 'SOH CAH TOA', trick: 'Sin=Opp/Hyp, Cos=Adj/Hyp, Tan=Opp/Adj', example: 'Remember right triangle ratios' },
  { category: 'Trigonometry Tricks', title: 'ASTC Rule (All Students Take Calculus)', trick: 'Q1: All+, Q2: Sin+, Q3: Tan+, Q4: Cos+', example: 'Sign of trig functions by quadrant' },
  { category: 'Trigonometry Tricks', title: 'Special Angles', trick: '0°: 0,1,0 | 30°: 1/2,√3/2,1/√3 | 45°: 1/√2,1/√2,1 | 60°: √3/2,1/2,√3 | 90°: 1,0,∞', example: 'sin, cos, tan order' },
  { category: 'Trigonometry Tricks', title: 'Complementary Angles', trick: 'sin(90°-θ) = cosθ, cos(90°-θ) = sinθ, tan(90°-θ) = cotθ', example: 'sin30° = cos60° = 1/2' },
  { category: 'Trigonometry Tricks', title: 'sin²θ + cos²θ = 1', trick: 'If sinθ = 3/5, cosθ = 4/5 (3-4-5 triangle). Always draw triangle!', example: 'Find other ratios from one' },
  { category: 'Trigonometry Tricks', title: 'Max/Min Values', trick: 'sinθ and cosθ: max=1, min=-1. |sinθ|+|cosθ| max = √2', example: 'Range of trig expressions' },
  { category: 'Trigonometry Tricks', title: 'Height & Distance', trick: 'Draw diagram! Mark angle of elevation/depression. Use tan for height, sin for slant.', example: 'h = d·tanθ' },
  { category: 'Trigonometry Tricks', title: 'Inverse Trig Domain', trick: 'sin⁻¹: [-1,1]→[-π/2,π/2]. cos⁻¹: [-1,1]→[0,π]. tan⁻¹: R→(-π/2,π/2)', example: 'Principal value ranges' },

  // ===== PHYSICS TRICKS =====
  { category: 'Physics Tricks', title: 'SI Units Trick', trick: 'Meter, Kilogram, Second, Ampere, Kelvin, Mole, Candela — "MaKe Sure All Kids Memorize"', example: '7 base SI units' },
  { category: 'Physics Tricks', title: 'F = ma Units', trick: '1 Newton = 1 kg·m/s². Force = mass × acceleration', example: 'Check dimensional consistency' },
  { category: 'Physics Tricks', title: 'Mirror/Lens Sign Convention', trick: 'Object distance (u) always negative. Real image v negative (mirror), positive (lens).', example: 'New Cartesian sign convention' },
  { category: 'Physics Tricks', title: 'Convex vs Concave', trick: 'Convex = outward curve = converging lens / diverging mirror. Concave = inward = opposite.', example: 'Cave goes in, vex bulges out' },
  { category: 'Physics Tricks', title: 'Series vs Parallel', trick: 'Series: same current, add R. Parallel: same voltage, add 1/R.', example: 'Resistors and capacitors opposite!' },
  { category: 'Physics Tricks', title: 'Power Formulas', trick: 'P=VI. If R known: P=I²R or P=V²/R. Use whichever has given values.', example: 'Pick easiest formula' },
  { category: 'Physics Tricks', title: 'Projectile at 45°', trick: 'Maximum range when angle = 45°. Range = u²/g', example: 'Complementary angles give same range' },
  { category: 'Physics Tricks', title: 'Heat Transfer', trick: 'Conduction (solid), Convection (fluid), Radiation (no medium). Thermos flask stops all three!', example: 'Vacuum + silvered surfaces' },
  { category: 'Physics Tricks', title: 'Sound vs Light', trick: 'Sound needs medium, light doesn\'t. Sound slower (~340 m/s), light fastest (3×10⁸ m/s).', example: 'Thunder after lightning' },
  { category: 'Physics Tricks', title: 'Pendulum Period', trick: 'T depends on L and g only, NOT mass! T = 2π√(L/g)', example: 'All pendulums same length → same period' },
  { category: 'Physics Tricks', title: 'Ohm\'s Law Triangle', trick: 'Cover what you need: V=IR, I=V/R, R=V/I', example: 'V over I×R triangle' },
  { category: 'Physics Tricks', title: 'Left Hand Rule (Motor)', trick: 'F(field) × I(current) = Motion. Thumb=Force, Index=Field, Middle=Current', example: 'Fleming\'s Left Hand Rule' },
  { category: 'Physics Tricks', title: 'Right Hand Rule (Generator)', trick: 'Motion × Field = Current. Thumb=Motion, Index=Field, Middle=Current', example: 'Fleming\'s Right Hand Rule' },
  { category: 'Physics Tricks', title: 'Density Trick', trick: 'Water = 1 g/cm³ = 1000 kg/m³. Objects with density < 1 float.', example: 'Ice floats (0.92), iron sinks (7.8)' },
  { category: 'Physics Tricks', title: 'Kinetic vs Potential', trick: 'KE at bottom, PE at top. Total mechanical energy conserved (no friction).', example: 'Roller coaster: max speed at bottom' },

  // ===== CHEMISTRY TRICKS =====
  { category: 'Chemistry Tricks', title: 'Periodic Table Groups', trick: 'Group 1: Alkali metals (Li,Na,K). Group 17: Halogens (F,Cl,Br,I). Group 18: Noble gases (He,Ne,Ar).', example: 'Last group = inert gases' },
  { category: 'Chemistry Tricks', title: 'Valency Trick', trick: 'Group number = valency (1-4). For 5-7: valency = 8 - group number.', example: 'Group 16 → valency 2, Group 7 → valency 1' },
  { category: 'Chemistry Tricks', title: 'OIL RIG', trick: 'Oxidation Is Loss (of electrons), Reduction Is Gain (of electrons)', example: 'Remember redox' },
  { category: 'Chemistry Tricks', title: 'Acid-Base Indicators', trick: 'Litmus: acid→red, base→blue. Phenolphthalein: base→pink. Methyl orange: acid→red, base→yellow.', example: 'Natural litmus from lichen' },
  { category: 'Chemistry Tricks', title: 'pH Scale', trick: '0-6 acidic, 7 neutral, 8-14 basic. pH + pOH = 14 always.', example: 'Stomach acid pH~2, soap pH~10' },
  { category: 'Chemistry Tricks', title: 'Common Acids', trick: 'HCl (stomach), H₂SO₄ (battery), HNO₃ (fertilizer), CH₃COOH (vinegar)', example: 'Memorize formulas + uses' },
  { category: 'Chemistry Tricks', title: 'Common Bases', trick: 'NaOH (caustic soda), KOH, Ca(OH)₂ (slaked lime), NH₄OH (ammonia)', example: 'Bases feel slippery' },
  { category: 'Chemistry Tricks', title: 'Metal Reactivity Series', trick: 'K > Na > Ca > Mg > Al > Zn > Fe > Pb > Cu > Ag > Au. "Please Send Charlie\'s Monkeys And Zebras In Large Cages Making All Children Gasp"', example: 'More reactive displaces less reactive' },
  { category: 'Chemistry Tricks', title: 'Allotropes of Carbon', trick: 'Diamond (hardest), Graphite (soft, conductor), Fullerene (C60), Graphene (single layer)', example: 'Same element, different structure' },
  { category: 'Chemistry Tricks', title: 'Hard Water', trick: 'Contains Ca²⁺ and Mg²⁺ salts. Removed by boiling, adding washing soda, or ion exchange.', example: 'Doesn\'t lather easily with soap' },
  { category: 'Chemistry Tricks', title: 'Fertilizers NPK', trick: 'N (Nitrogen) → leaf growth. P (Phosphorus) → root/flower. K (Potassium) → overall health.', example: 'Urea = nitrogen fertilizer' },
  { category: 'Chemistry Tricks', title: 'Rusting Conditions', trick: 'Iron + Oxygen + Water = Rust (Fe₂O₃·xH₂O). Prevent: paint, galvanize, oil.', example: 'Both O₂ and H₂O needed' },
  { category: 'Chemistry Tricks', title: 'Mole Concept', trick: '1 mole = 6.022×10²³ particles = molar mass in grams. At STP: 1 mole gas = 22.4 L', example: 'Bridge between atomic and macroscopic' },

  // ===== ENGLISH TRICKS =====
  { category: 'English Tricks', title: 'Subject-Verb Agreement', trick: 'Each, every, everyone, nobody → SINGULAR verb. "Each of the boys IS..."', example: 'Indefinite pronouns = singular' },
  { category: 'English Tricks', title: 'Between vs Among', trick: 'Between = 2 things/people. Among = 3 or more.', example: 'Between you and me (not I)' },
  { category: 'English Tricks', title: 'Lay vs Lie', trick: 'Lay = put something down (needs object). Lie = recline (no object). Lay-laid-laid, Lie-lay-lain.', example: 'Chickens lay eggs, humans lie down' },
  { category: 'English Tricks', title: 'Affect vs Effect', trick: 'Affect = verb (to influence). Effect = noun (result). "RAVEN": Remember Affect Verb, Effect Noun.', example: 'The rain affected the game. The effect was a delay.' },
  { category: 'English Tricks', title: 'Fewer vs Less', trick: 'Fewer = countable (fewer apples). Less = uncountable (less water).', example: 'Supermarket "10 items or fewer"' },
  { category: 'English Tricks', title: 'Who vs Whom', trick: 'Who = subject (he). Whom = object (him). Replace with he/him to check.', example: 'Who called? He called. Whom did you see? I saw him.' },
  { category: 'English Tricks', title: 'Common Confusions', trick: 'Its = possessive. It\'s = it is. Your = possessive. You\'re = you are. Their/there/they\'re.', example: 'Apostrophe = contraction' },
  { category: 'English Tricks', title: 'Synonym Groups', trick: 'Happy: elated, jubilant, ecstatic. Sad: melancholy, despondent. Big: enormous, colossal.', example: 'Group by intensity' },
  { category: 'English Tricks', title: 'Idiom Meanings', trick: 'Break the ice = start conversation. Spill the beans = reveal secret. Hit the nail on the head = exactly right.', example: 'Learn 5 idioms daily' },
  { category: 'English Tricks', title: 'One Word Substitution', trick: 'One who loves mankind = Philanthropist. One who hates mankind = Misanthrope. Study of birds = Ornithology.', example: 'High frequency in NDA' },
  { category: 'English Tricks', title: 'Reading Comprehension', trick: 'Read questions FIRST, then passage. Underline key words. Eliminate wrong options.', example: 'Saves time in exam' },
  { category: 'English Tricks', title: 'Error Spotting', trick: 'Check: subject-verb, tense consistency, article (a/an/the), preposition, parallelism.', example: 'Read sentence aloud mentally' },

  // ===== HISTORY MNEMONICS =====
  { category: 'History Mnemonics', title: 'Indus Valley Sites', trick: 'HMHL = Harappa, Mohenjo-daro, Harappa, Lothal. "Great Bath" at Mohenjo-daro.', example: 'Major archaeological sites' },
  { category: 'History Mnemonics', title: 'Mauryan Rulers', trick: 'Chandragupta → Bindusara → Ashoka. Ashoka fought Kalinga war (261 BC), then embraced Buddhism.', example: 'First pan-Indian empire' },
  { category: 'History Mnemonics', title: 'Delhi Sultanate', trick: 'SLKLT = Slave, Khilji, Tughlaq, Lodi. Qutub Minar was built by Qutub-ud-din Aibak.', example: '5 dynasties in chronological order' },
  { category: 'History Mnemonics', title: 'Mughal Emperors', trick: 'BHAJASAS = Babur, Humayun, Akbar, Jahangir, Shah Jahan, Aurangzeb, Bahadur Shah', example: 'Babur founded in 1526' },
  { category: 'History Mnemonics', title: 'Freedom Movement Timeline', trick: '1885 Congress | 1905 Partition Bengal | 1919 Jallianwala | 1920 Non-Coop | 1930 Dandi March | 1942 Quit India | 1947 Independence', example: 'Key dates in order' },
  { category: 'History Mnemonics', title: 'Governors General', trick: 'WCBCD = Warren Hastings, Cornwallis (Permanent Settlement), Bentinck (Sati abolition), Dalhousie (Railways, Doctrine of Lapse)', example: 'British administration' },
  { category: 'History Mnemonics', title: 'World Wars', trick: 'WWI: 1914-1918 (Sarajevo assassination). WWII: 1939-1945 (Germany invaded Poland).', example: 'Alliances: Triple Entente vs Central Powers' },
  { category: 'History Mnemonics', title: 'French Revolution', trick: '1789 — Bastille Day (July 14). Liberty, Equality, Fraternity. Napoleon rose 1799.', example: 'End of monarchy in France' },
  { category: 'History Mnemonics', title: 'Russian Revolution', trick: '1917 — Bolsheviks under Lenin. "Peace, Land, Bread" slogan. USSR formed 1922.', example: 'End of Tsarist rule' },
  { category: 'History Mnemonics', title: 'American Independence', trick: '1776 — Declaration by Thomas Jefferson. George Washington = first President.', example: 'Boston Tea Party 1773' },

  // ===== GEOGRAPHY TRICKS =====
  { category: 'Geography Tricks', title: 'Tropic of Cancer States', trick: '8 states: Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, WB, Tripura, Mizoram. "GRaM C J WTM"', example: '23.5°N latitude' },
  { category: 'Geography Tricks', title: 'Standard Meridian', trick: '82.5°E passes through Mirzapur (UP). IST = GMT + 5:30', example: 'India has 1 time zone' },
  { category: 'Geography Tricks', title: 'Longest to Shortest Rivers', trick: 'Ganga > Godavari > Krishna > Yamuna > Narmada. Ganga originates Gangotri.', example: 'Indian river systems' },
  { category: 'Geography Tricks', title: 'Himalayan Ranges (West to East)', trick: 'Pir Panjal, Dhauladhar, Kumaon, Nepal, Sikkim, Bhutan, Arunachal. "Pirates Don\'t Kill Nice Soldiers Boldly Always"', example: 'Parallel ranges' },
  { category: 'Geography Tricks', title: 'Indian States by Area', trick: 'Rajasthan (largest) > MP > Maharashtra > ... > Goa (smallest)', example: 'RAJ = largest' },
  { category: 'Geography Tricks', title: 'Indian States by Population', trick: 'UP (largest) > Maharashtra > Bihar > ... > Sikkim (smallest)', example: 'UP alone ~17% of India' },
  { category: 'Geography Tricks', title: 'Major Crops', trick: 'Rice: WB, UP, Punjab. Wheat: UP, Punjab, MP. Cotton: Gujarat, Maharashtra. Tea: Assam. Coffee: Karnataka.', example: 'State-crop association' },
  { category: 'Geography Tricks', title: 'Minerals', trick: 'Iron: Odisha, Jharkhand. Coal: Jharkhand, Chhattisgarh. Bauxite: Odisha. Mica: Jharkhand. Gold: Karnataka.', example: 'Mining states' },
  { category: 'Geography Tricks', title: 'Ports', trick: 'Mumbai (natural, largest). Chennai, Kolkata (riverine). Vishakhapatnam (deepest). Kandla (tidal).', example: 'East vs West coast ports' },
  { category: 'Geography Tricks', title: 'Climate Types', trick: 'Tropical: hot year-round. Mediterranean: dry summers. Desert: <25cm rain. Monsoon: seasonal reversal of winds.', example: 'India = tropical monsoon' },
  { category: 'Geography Tricks', title: 'Atmosphere Layers', trick: 'Troposphere (weather) → Stratosphere (ozone) → Mesosphere → Thermosphere → Exosphere', example: 'Troposphere = where we live' },
  { category: 'Geography Tricks', title: 'Rock Types', trick: 'Igneous (cooled magma, granite). Sedimentary (layers, sandstone). Metamorphic (heat+pressure, marble).', example: 'Rock cycle' },

  // ===== POLITY TRICKS =====
  { category: 'Polity Tricks', title: 'Fundamental Rights (6)', trick: 'Right to Equality (14-18), Freedom (19-22), Against Exploitation (23-24), Religion (25-28), Culture (29-30), Constitutional Remedies (32)', example: 'Article 32 = heart & soul' },
  { category: 'Polity Tricks', title: 'DPSP (Part IV)', trick: 'Not enforceable but fundamental in governance. Socialist, Gandhian, Liberal-Intellectual principles.', example: 'Article 36-51' },
  { category: 'Polity Tricks', title: 'Parliament', trick: 'Lok Sabha: max 552, term 5 years. Rajya Sabha: max 250, permanent, 1/3 retire every 2 years.', example: 'Money bills only in Lok Sabha' },
  { category: 'Polity Tricks', title: 'President Election', trick: 'Electoral College: MPs + MLAs. Value of vote differs. Term: 5 years. Impeachment: Art 61.', example: 'Ceremonial head' },
  { category: 'Polity Tricks', title: 'PM Appointment', trick: 'Leader of majority party in Lok Sabha. PM advises President on Council of Ministers.', example: 'Real executive power' },
  { category: 'Polity Tricks', title: 'Judiciary', trick: 'Supreme Court (Apex, Art 124). High Courts (state level). District Courts. PIL allowed.', example: 'Guardian of Constitution' },
  { category: 'Polity Tricks', title: 'Amendment Process', trick: 'Simple majority (5 subjects). Special majority (most). Special + state ratification (federal structure).', example: 'Art 368' },
  { category: 'Polity Tricks', title: 'Emergency Types', trick: 'National (Art 352, war/external aggression). State/President\'s Rule (Art 356). Financial (Art 360).', example: 'Only once financial emergency (never used)' },
  { category: 'Polity Tricks', title: 'Schedules (12)', trick: '1st: States/UTs. 7th: Division of powers. 8th: Languages. 9th: Land reforms. 10th: Anti-defection.', example: 'Originally 8, now 12' },
  { category: 'Polity Tricks', title: 'Panchayati Raj', trick: '73rd Amendment (1992). 3 tiers: Village, Block, District. 1/3 seats reserved for women.', example: 'Grassroots democracy' },

  // ===== EXAM HACKS =====
  { category: 'Exam Hacks', title: 'Negative Marking Strategy', trick: 'Sure → attempt. 50-50 → attempt if 3+ options eliminated. Pure guess → SKIP. Math: skip lengthy questions first.', example: '1/3 marks lost per wrong answer' },
  { category: 'Exam Hacks', title: 'OMR Filling', trick: 'Fill circles completely. No stray marks. Carry extra pencils. Fill as you go, not at end.', example: 'Wrong OMR = rejected' },
  { category: 'Exam Hacks', title: '3-Pass Strategy', trick: 'Pass 1: Easy questions (60 min). Pass 2: Medium (50 min). Pass 3: Hard + review (40 min).', example: 'Never get stuck on one question' },
  { category: 'Exam Hacks', title: 'Elimination Method', trick: 'In MCQs, eliminate obviously wrong options first. Often narrows to 2 choices.', example: 'Improves guess accuracy to 50%' },
  { category: 'Exam Hacks', title: 'Math Time Saver', trick: 'Work backwards from the options! Substitute answer choices into the equation. Use approximation for large numbers.', example: 'Reverse solving saves time' },
  { category: 'Exam Hacks', title: 'English RC Strategy', trick: 'Read the questions first. Find keywords in the passage. Questions about tone and the author\'s view are very common.', example: 'Do not read the entire passage in depth' },
  { category: 'Exam Hacks', title: 'GK Speed Round', trick: 'History/Geography: dates and names. Science: cause-effect. Current affairs: last 6 months focus.', example: '30 seconds max per GK question' },
  { category: 'Exam Hacks', title: 'Guess Smartly', trick: 'No pattern in answer key. But if stuck, same letter for all guesses is statistically same as random.', example: 'Never leave if you can eliminate 1 option' },
  { category: 'Exam Hacks', title: 'Exam Day Checklist', trick: 'Admit card, photo ID, 2 pencils, eraser, sharpener, water bottle, watch. Reach 30 min early.', example: 'No calculator allowed' },
  { category: 'Exam Hacks', title: 'Last 10 Minutes', trick: 'Review marked questions. Check OMR alignment. Fill any blanks. Don\'t start new tough questions.', example: 'Verify roll number on OMR' },

  // ===== MEMORY TRICKS =====
  { category: 'Memory Tricks', title: 'Planets Order', trick: 'My Very Educated Mother Just Served Us Noodles = Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune', example: 'Pluto no longer a planet' },
  { category: 'Memory Tricks', title: 'Taxonomy Order', trick: 'King Philip Came Over For Good Soup = Kingdom, Phylum, Class, Order, Family, Genus, Species', example: 'Biological classification' },
  { category: 'Memory Tricks', title: 'Electromagnetic Spectrum', trick: 'Radio, Microwave, Infrared, Visible, UV, X-ray, Gamma = Rabbits Mate In Very Unusual eXpensive Gardens', example: 'Low to high frequency' },
  { category: 'Memory Tricks', title: 'Human Blood Groups', trick: 'A has A antigen, B has B antigen, AB has both, O has neither. Rh+ has Rh factor.', example: 'O is universal donor' },
  { category: 'Memory Tricks', title: 'Vitamins', trick: 'Fat-soluble: A, D, E, K ("All Dogs Eat Kittens"). Water-soluble: B complex, C.', example: 'Deficiency diseases' },
  { category: 'Memory Tricks', title: 'Noble Gases', trick: 'He Ne Ar Kr Xe Rn — "Henry Never Argued, Kicked Xenon Running"', example: 'Group 18, inert' },
  { category: 'Memory Tricks', title: 'Indian Nobel Laureates', trick: 'Rabindranath Tagore (Literature 1913), CV Raman (Physics 1930), Mother Teresa (Peace 1979), Amartya Sen (Economics 1998)', example: 'Know their fields' },
  { category: 'Memory Tricks', title: 'Important Dates', trick: '26 Jan 1950 (Republic), 15 Aug 1947 (Independence), 26 Nov 1949 (Constitution adopted), 2 Oct (Gandhi Jayanti)', example: 'National holidays' }
];

const GK_FACTS = [
  { category: 'India', title: 'National Symbols', facts: ['National Flag: Tricolour (saffron, white, green)', 'National Emblem: Sarnath Lion Capital', 'National Anthem: Jana Gana Mana (Rabindranath Tagore)', 'National Song: Vande Mataram (Bankim Chandra)', 'National Bird: Peacock', 'National Animal: Bengal Tiger', 'National Flower: Lotus', 'National Fruit: Mango', 'National Tree: Banyan'] },
  { category: 'India', title: 'Constitution Facts', facts: ['Longest written constitution in the world', '448 articles, 12 schedules, 105 amendments', 'Borrowed from: UK (Parliament), USA (Fundamental Rights), Ireland (DPSP), Canada (Federalism)', 'Drafted by Dr. B.R. Ambedkar', 'Took 2 years 11 months 18 days to frame'] },
  { category: 'India', title: 'Defence', facts: ['Indian Army: Founded 1895, Motto "Service Before Self"', 'Indian Navy: Founded 1612, Motto "May the Lord of Water be auspicious"', 'Indian Air Force: Founded 1932, Motto "Touch the Sky with Glory"', 'NDA: Khadakwasla, Pune (established 1954)', 'IMA: Dehradun', 'OTA: Chennai & Gaya', 'Navy Academy: Ezhimala, Kerala'] },
  { category: 'World', title: 'Important Organizations', facts: ['UN: 1945, HQ New York, 193 members', 'NATO: 1949, military alliance', 'WHO: 1948, HQ Geneva', 'IMF: 1944, HQ Washington', 'World Bank: 1944', 'SAARC: 1985, 8 members', 'ASEAN: 1967, 10 members', 'BRICS: Brazil, Russia, India, China, South Africa'] },
  { category: 'Science', title: 'Important Scientists', facts: ['Newton: Laws of Motion, Gravity', 'Einstein: Relativity, E=mc²', 'Darwin: Theory of Evolution', 'Mendel: Laws of Inheritance', 'Curie: Radioactivity (2 Nobel Prizes)', 'Tesla: AC current', 'CV Raman: Raman Effect (Nobel 1930)', 'APJ Abdul Kalam: Missile Man of India'] },
  { category: 'Geography', title: 'World Records', facts: ['Largest country: Russia', 'Most populous: India (surpassed China)', 'Longest river: Nile (Africa)', 'Highest mountain: Everest (8848.86m)', 'Largest desert: Sahara', 'Deepest ocean trench: Mariana Trench', 'Largest ocean: Pacific', 'Smallest country: Vatican City'] },
  { category: 'History', title: 'Battles & Wars', facts: ['Battle of Plassey: 1757 (British victory)', 'Battle of Buxar: 1764', 'First Battle of Panipat: 1526 (Babur vs Ibrahim Lodi)', 'Third Battle of Panipat: 1761 (Marathas defeated)', 'Battle of Tarain: 1192 (Prithviraj Chauhan defeated)', 'Kalinga War: 261 BC (Ashoka)'] },
  { category: 'Economics', title: 'Key Terms', facts: ['GDP: Total value of goods & services produced', 'GNP: GDP + net income from abroad', 'Inflation: General rise in prices', 'Deflation: General fall in prices', 'Fiscal Deficit: Govt expenditure > revenue', 'Repo Rate: Rate at which RBI lends to banks', 'GST: Goods & Services Tax (2017)'] }
];

const VOCABULARY = [
  { word: 'Abundant', meaning: 'Plentiful, in large quantity', synonym: 'Plentiful', antonym: 'Scarce' },
  { word: 'Benevolent', meaning: 'Kind, well-meaning', synonym: 'Kind', antonym: 'Malevolent' },
  { word: 'Candid', meaning: 'Honest, straightforward', synonym: 'Frank', antonym: 'Evasive' },
  { word: 'Diligent', meaning: 'Hardworking, careful', synonym: 'Industrious', antonym: 'Lazy' },
  { word: 'Ephemeral', meaning: 'Short-lived, transient', synonym: 'Fleeting', antonym: 'Permanent' },
  { word: 'Frugal', meaning: 'Economical, thrifty', synonym: 'Thrifty', antonym: 'Extravagant' },
  { word: 'Gregarious', meaning: 'Sociable, fond of company', synonym: 'Outgoing', antonym: 'Reclusive' },
  { word: 'Hackneyed', meaning: 'Overused, unoriginal', synonym: 'Clichéd', antonym: 'Original' },
  { word: 'Impetuous', meaning: 'Acting without thought', synonym: 'Rash', antonym: 'Cautious' },
  { word: 'Jubilant', meaning: 'Very happy, celebrating', synonym: 'Elated', antonym: 'Despondent' },
  { word: 'Keen', meaning: 'Eager, sharp', synonym: 'Eager', antonym: 'Reluctant' },
  { word: 'Lethargic', meaning: 'Sluggish, lacking energy', synonym: 'Sluggish', antonym: 'Energetic' },
  { word: 'Meticulous', meaning: 'Very careful, detailed', synonym: 'Precise', antonym: 'Careless' },
  { word: 'Naive', meaning: 'Inexperienced, innocent', synonym: 'Innocent', antonym: 'Worldly' },
  { word: 'Obsolete', meaning: 'Outdated, no longer used', synonym: 'Outdated', antonym: 'Modern' },
  { word: 'Pragmatic', meaning: 'Practical, realistic', synonym: 'Practical', antonym: 'Idealistic' },
  { word: 'Quintessential', meaning: 'Most perfect example', synonym: 'Typical', antonym: 'Atypical' },
  { word: 'Resilient', meaning: 'Able to recover quickly', synonym: 'Tough', antonym: 'Fragile' },
  { word: 'Scrupulous', meaning: 'Very careful about honesty', synonym: 'Conscientious', antonym: 'Unscrupulous' },
  { word: 'Taciturn', meaning: 'Reserved, saying little', synonym: 'Reticent', antonym: 'Talkative' },
  { word: 'Ubiquitous', meaning: 'Present everywhere', synonym: 'Omnipresent', antonym: 'Rare' },
  { word: 'Verbose', meaning: 'Using too many words', synonym: 'Wordy', antonym: 'Concise' },
  { word: 'Wary', meaning: 'Cautious, on guard', synonym: 'Cautious', antonym: 'Trusting' },
  { word: 'Zealous', meaning: 'Passionately devoted', synonym: 'Passionate', antonym: 'Apathetic' },
  { word: 'Altruistic', meaning: 'Selfless, concerned for others', synonym: 'Selfless', antonym: 'Selfish' },
  { word: 'Belligerent', meaning: 'Hostile, aggressive', synonym: 'Aggressive', antonym: 'Peaceful' },
  { word: 'Capricious', meaning: 'Unpredictable, changeable', synonym: 'Fickle', antonym: 'Steadfast' },
  { word: 'Debilitate', meaning: 'Weaken, make feeble', synonym: 'Weaken', antonym: 'Strengthen' },
  { word: 'Eloquent', meaning: 'Fluent and persuasive', synonym: 'Articulate', antonym: 'Inarticulate' },
  { word: 'Fastidious', meaning: 'Very attentive to detail', synonym: 'Particular', antonym: 'Easygoing' }
];

const IDIOMS = [
  { idiom: 'A piece of cake', meaning: 'Very easy' },
  { idiom: 'Break the ice', meaning: 'Start a conversation' },
  { idiom: 'Beat around the bush', meaning: 'Avoid the main topic' },
  { idiom: 'Bite the bullet', meaning: 'Face a difficult situation bravely' },
  { idiom: 'Cost an arm and a leg', meaning: 'Very expensive' },
  { idiom: 'Hit the nail on the head', meaning: 'Be exactly right' },
  { idiom: 'Let the cat out of the bag', meaning: 'Reveal a secret' },
  { idiom: 'Once in a blue moon', meaning: 'Very rarely' },
  { idiom: 'Spill the beans', meaning: 'Reveal secret information' },
  { idiom: 'The ball is in your court', meaning: 'It\'s your decision/responsibility' },
  { idiom: 'Under the weather', meaning: 'Feeling ill' },
  { idiom: 'When pigs fly', meaning: 'Something impossible' },
  { idiom: 'Burn the midnight oil', meaning: 'Work late into the night' },
  { idiom: 'Call it a day', meaning: 'Stop working' },
  { idiom: 'Cut corners', meaning: 'Do something cheaply or badly' },
  { idiom: 'Get cold feet', meaning: 'Become nervous and change mind' },
  { idiom: 'In hot water', meaning: 'In trouble' },
  { idiom: 'Keep your chin up', meaning: 'Stay positive' },
  { idiom: 'Miss the boat', meaning: 'Miss an opportunity' },
  { idiom: 'Pull someone\'s leg', meaning: 'Joke or tease someone' }
];
