plugins {
    id 'com.android.application' version '8.3.0' apply false
}
Aur settings.gradle edit karo:
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "SpinPlayApp"
include ':app'
