plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rebel.panel'
    compileSdk 34

    defaultConfig {
        applicationId "com.rebel.panel"
        minSdk 24
        targetSdk 34
        versionCode 11
        versionName "3.0.0"
        buildConfigField "String", "REBEL_APP_SECRET", "\"rbl_app_xK9m2pQ7nL4wR8vT3hJ6fY1bN5cD0eA\""
        buildConfigField "String", "REBEL_APK_SHA256", "\"570290715E067531A5DF06DD139604192A70993C863E97F51A09609F8A702CECA\""
        buildConfigField "String", "SSL_PIN_PRIMARY", "\"sha256/SM2goQ/B0xk7U8iezGH0VeeoZwZWiEC9obc8uSCte8=\""
        buildConfigField "String", "SSL_PIN_BACKUP", "\"sha256/C5+lp5BmfbMGadTPwzoIB6l9a6Fi4EioGsliyc1tirc=\""
        buildConfigField "boolean", "SSL_PIN_ENFORCE", "true"
    }

    buildTypes {
        debug {
            minifyEnabled false
            debuggable true
            buildConfigField "boolean", "SSL_PIN_ENFORCE", "false"
        }
        release {
            minifyEnabled true
            shrinkResources true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.security:security-crypto:1.1.0-alpha06'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
